/**
 * Alfanumrik — Foxy Conversation Continuity, Phase 4 (2026-05-18).
 *
 * Cross-session pedagogical memory: load the student's most recent monthly
 * synthesis + a high/low mastery snapshot + top misconceptions, and format
 * them into a `LEARNER MEMORY` prompt block that Foxy can use to anchor a
 * fresh turn against what the student has already covered, mastered, or
 * struggled with over the past ~30 days.
 *
 * Why a sibling helper (not a `loadCognitiveContext` extension):
 *  - The cognitive context loader is chapter-scoped and runs every turn.
 *    Long memory is subject-scoped, slower-moving, and orthogonal — keeping
 *    it isolated lets us flag-gate independently and unit-test without
 *    pulling 1300 LOC of route.ts dependencies into the test harness.
 *
 * PII discipline (P13 — non-negotiable):
 *  - The `summary_text_en` field in `monthly_synthesis_runs` is generated by
 *    `buildSynthesisSummaryPrompt` (src/lib/ai/workflows/synthesis-summary.ts),
 *    which DOES inject `studentName` and `studentGrade` into the system
 *    prompt that produces the parent-share text. The resulting text often
 *    contains the student's first name in phrases like "Aarav showed strong
 *    progress…" or "Dear parent, Aarav has…".
 *  - Before any portion of `summary_text_en` is forwarded to Foxy's system
 *    prompt we MUST scrub the student name. The route caller passes the
 *    name explicitly (fetched from `students.name`) and this module
 *    additionally applies a generic "Dear X" / "X's" / address-line scrub
 *    as defense-in-depth.
 *  - Concept names, Bloom levels, and curated misconception labels are
 *    content-only by construction (editor-curated, never include student
 *    data). They are safe to forward as-is.
 *
 * Source tables (all already in production):
 *  - `monthly_synthesis_runs` (migration 20260511000000) — per-(student,
 *    month) row with `summary_text_en`, `summary_text_hi`, `bundle` JSONB.
 *  - `concept_mastery` — already partially read by `loadCognitiveContext`;
 *    we re-derive a simpler "top 3 high / top 3 low" projection here so
 *    the LEARNER MEMORY block is self-contained and stable.
 *  - `recentMisconceptions` — sourced from the already-loaded
 *    `CognitiveContext.recentMisconceptions` (the loader does the join
 *    work; we just project the labels).
 *
 * Feature flag: `ff_foxy_long_memory_v1` (migration 20260528000014).
 * Default OFF. When OFF, the route MUST short-circuit before calling
 * `loadLongMemorySnapshot` so we don't pay the DB roundtrip.
 *
 * Plan: docs/superpowers/plans/2026-05-18-foxy-conversation-continuity-fix.md
 *       (Phase 4 of 4)
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import { logger } from '@alfanumrik/lib/logger';

// ─── Public types ───────────────────────────────────────────────────────────

export interface LongMemorySnapshot {
  /** YYYY-MM of the most recent monthly synthesis row, or null if none. */
  synthesis_month: string | null;
  /**
   * Scrubbed synthesis text (capped at 500 chars). null when the most-recent
   * row has empty `summary_text_en` (the lazy-fill in /api/synthesis/state
   * may not have run yet for new students).
   */
  synthesis_summary: string | null;
  /** Top 3 concept titles where mastery_probability >= 0.8 for this subject. */
  high_concepts: string[];
  /** Top 3 concept titles where mastery_probability < 0.6 for this subject. */
  low_concepts: string[];
  /**
   * Top 3 curated misconception labels observed in recent quizzes.
   * Editor-authored, content-only — never contains PII.
   */
  top_misconceptions: string[];
}

export const EMPTY_LONG_MEMORY: LongMemorySnapshot = {
  synthesis_month: null,
  synthesis_summary: null,
  high_concepts: [],
  low_concepts: [],
  top_misconceptions: [],
};

// ─── PII scrub ──────────────────────────────────────────────────────────────

const SYNTHESIS_TEXT_MAX = 500;

/**
 * Strip the student's first/last name from synthesis text. Belt-and-braces
 * because the upstream prompt template injects `Student: ${studentName}` so
 * the model often parrots the name back in the output.
 *
 * - Case-insensitive whole-word match (so "Ram" doesn't match "Rama").
 * - Replaces with `the student` so the resulting prose still reads naturally.
 * - Also strips common address-line patterns: "Dear X", "X's", "for X".
 *
 * Does NOT attempt to redact arbitrary other names that might appear in the
 * synthesis — those would not be PII relative to the same student.
 */
export function scrubStudentName(text: string, studentName: string | null | undefined): string {
  if (!text) return '';
  let out = text;
  const name = (studentName ?? '').trim();
  if (name.length >= 2) {
    // Split on whitespace to handle "First Last" — scrub each token.
    const tokens = name.split(/\s+/).filter((t) => t.length >= 2);
    for (const token of tokens) {
      // Escape regex metacharacters in the token before injecting into a pattern.
      const escaped = token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      // \b word boundaries + case-insensitive. Replace with "the student" so the
      // sentence reads naturally.
      out = out.replace(new RegExp(`\\b${escaped}\\b`, 'gi'), 'the student');
    }
  }
  // Defense-in-depth: common address-line collapse. After name scrub these
  // become "Dear the student" / "the student's progress" — collapse them.
  out = out.replace(/\bDear\s+the\s+student\b/gi, 'Dear parent');
  out = out.replace(/\bthe\s+student'?s\b/gi, "the student's");
  // Collapse repeated whitespace introduced by scrubbing.
  out = out.replace(/[ \t]+/g, ' ').replace(/\s+\n/g, '\n');
  return out.trim();
}

// ─── Loader ─────────────────────────────────────────────────────────────────

/**
 * Service-role required: this function reads `monthly_synthesis_runs` and
 * `concept_mastery` across subjects, neither of which is permitted to the
 * student via RLS in the read paths used here (curriculum_topics join).
 *
 * Best-effort: every block is wrapped in try/catch. A single block failure
 * yields an empty list for that block; full failure returns EMPTY_LONG_MEMORY.
 *
 * @param supabase  service-role client
 * @param studentId students.id
 * @param subject   subject code (lowercase, e.g. "physics", "math")
 * @param studentName plain text from students.name — used to scrub the
 *                  synthesis summary text. Pass null/empty if unknown
 *                  (we still apply the generic address-line scrub).
 * @param recentMisconceptionLabels labels already loaded by `loadCognitiveContext`.
 *                  Pass cognitiveCtx.recentMisconceptions.map(m => m.label).
 */
export async function loadLongMemorySnapshot(
  supabase: SupabaseClient,
  studentId: string,
  subject: string,
  studentName: string | null,
  recentMisconceptionLabels: string[] = [],
): Promise<LongMemorySnapshot> {
  try {
    // Resolve subject_id for the mastery scope.
    let subjectId: string | null = null;
    try {
      const { data: subjectRow } = await supabase
        .from('subjects')
        .select('id')
        .ilike('code', subject)
        .maybeSingle();
      subjectId = subjectRow?.id ?? null;
    } catch {
      // Non-fatal — fall through to subject-wide mastery (return [] below).
    }

    // Parallel-load: latest synthesis row + mastery slice.
    let synthesisMonth: string | null = null;
    let synthesisSummary: string | null = null;
    let highConcepts: string[] = [];
    let lowConcepts: string[] = [];

    // Note: Supabase's PostgrestBuilder is a thenable (PromiseLike), not a
    // full Promise. We use the two-arg `.then(onFulfill, onReject)` form
    // instead of `.catch()` because PromiseLike does not declare `.catch`.
    const synthesisPromise: Promise<void> = Promise.resolve(
      supabase
        .from('monthly_synthesis_runs')
        .select('synthesis_month, summary_text_en')
        .eq('student_id', studentId)
        .order('synthesis_month', { ascending: false })
        .limit(1)
        .maybeSingle(),
    ).then(
      (res: { data: unknown; error: unknown }) => {
        if (res.error) return;
        const row = res.data as { synthesis_month: string; summary_text_en: string } | null;
        if (!row) return;
        synthesisMonth = row.synthesis_month;
        const raw = (row.summary_text_en ?? '').trim();
        if (raw.length === 0) return;
        const scrubbed = scrubStudentName(raw, studentName);
        synthesisSummary = scrubbed.length > SYNTHESIS_TEXT_MAX
          ? `${scrubbed.slice(0, SYNTHESIS_TEXT_MAX - 1).trimEnd()}…`
          : scrubbed;
      },
      () => {
        // swallow — empty synthesis is acceptable
      },
    );

    const masteryPromise: Promise<void> = subjectId
      ? Promise.resolve(
          supabase
            .from('concept_mastery')
            .select('mastery_probability, topic_id, curriculum_topics!inner(title, subject_id)')
            .eq('student_id', studentId)
            .order('mastery_probability', { ascending: false })
            .limit(60),
        ).then(
          (res: { data: unknown; error: unknown }) => {
            if (res.error) return;
            type Row = {
              mastery_probability: number | null;
              curriculum_topics:
                | { title: string; subject_id: string }
                | Array<{ title: string; subject_id: string }>
                | null;
            };
            const rows = ((res.data as Row[] | null) ?? []) as Row[];
            const filtered = rows
              .map((r) => {
                const ct = Array.isArray(r.curriculum_topics)
                  ? r.curriculum_topics[0]
                  : r.curriculum_topics;
                if (!ct) return null;
                if (ct.subject_id !== subjectId) return null;
                return {
                  title: ct.title,
                  p: Number(r.mastery_probability ?? 0),
                };
              })
              .filter((r): r is NonNullable<typeof r> => r !== null);
            highConcepts = filtered
              .filter((r) => r.p >= 0.8)
              .slice(0, 3)
              .map((r) => r.title);
            lowConcepts = filtered
              .filter((r) => r.p < 0.6)
              .sort((a, b) => a.p - b.p)
              .slice(0, 3)
              .map((r) => r.title);
          },
          () => {
            // swallow
          },
        )
      : Promise.resolve();

    await Promise.all([synthesisPromise, masteryPromise]);

    // Project caller-supplied misconception labels (already loaded by the
    // cognitive context). Cap at 3 and trim whitespace. We don't re-query.
    const topMisconceptions = (recentMisconceptionLabels ?? [])
      .filter((l): l is string => typeof l === 'string' && l.trim().length > 0)
      .slice(0, 3)
      .map((l) => l.trim());

    // P13: do NOT log studentId paired with concept titles or misconception
    // labels. Counts only.
    logger.info('foxy_long_memory_loaded', {
      // intentionally NO studentId
      hasSynthesis: synthesisSummary !== null,
      highCount: highConcepts.length,
      lowCount: lowConcepts.length,
      misconceptionCount: topMisconceptions.length,
    });

    return {
      synthesis_month: synthesisMonth,
      synthesis_summary: synthesisSummary,
      high_concepts: highConcepts,
      low_concepts: lowConcepts,
      top_misconceptions: topMisconceptions,
    };
  } catch (err) {
    logger.warn('foxy_long_memory_failed', {
      error: err instanceof Error ? err.message : String(err),
      // P13: don't pair studentId with the failure event at warn level.
    });
    return EMPTY_LONG_MEMORY;
  }
}

// ─── Prompt section builder ─────────────────────────────────────────────────

/**
 * Render the snapshot into a `LEARNER MEMORY` prompt block. Empty when all
 * fields are empty — the foxy_tutor_v1 template uses `{{learner_memory_section}}`
 * which substitutes empty cleanly.
 *
 * Format (terse, ~150-200 tokens upper bound):
 *
 *   LEARNER MEMORY (last 30 days):
 *   - Subjects mastered: photosynthesis, food chains, energy flow
 *   - Subjects struggling: cell division, mitosis, meiosis
 *   - Most recent monthly synthesis (2026-04): The student showed strong
 *     progress in nutrition and photosynthesis. Light month for chemistry…
 *   - Common misconceptions to watch for: confuses mass with weight;
 *     mixes up oxidation vs reduction
 *
 * Use this only as background — Foxy must still answer the student's
 * CURRENT turn. Section is positioned AFTER previous_session_context in
 * the template (general → specific reading order).
 */
export function buildLongMemoryPromptSection(mem: LongMemorySnapshot): string {
  if (
    !mem.synthesis_summary
    && mem.high_concepts.length === 0
    && mem.low_concepts.length === 0
    && mem.top_misconceptions.length === 0
  ) {
    return '';
  }

  const lines: string[] = ['## LEARNER MEMORY (last 30 days)'];
  if (mem.high_concepts.length > 0) {
    lines.push(`- Mastered concepts: ${mem.high_concepts.join(', ')}`);
  }
  if (mem.low_concepts.length > 0) {
    lines.push(`- Struggling concepts: ${mem.low_concepts.join(', ')}`);
  }
  if (mem.synthesis_summary && mem.synthesis_month) {
    // Already scrubbed + truncated inside loadLongMemorySnapshot, but we
    // re-truncate here as a defense against direct callers passing raw text.
    const safe = mem.synthesis_summary.length > SYNTHESIS_TEXT_MAX
      ? `${mem.synthesis_summary.slice(0, SYNTHESIS_TEXT_MAX - 1).trimEnd()}…`
      : mem.synthesis_summary;
    lines.push(`- Recent monthly synthesis (${mem.synthesis_month}): ${safe}`);
  }
  if (mem.top_misconceptions.length > 0) {
    lines.push(
      `- Misconceptions to watch for: ${mem.top_misconceptions.slice(0, 3).join('; ')}`,
    );
  }
  lines.push(
    'Use this as background only. Do NOT address it directly — the student\'s current question is in the user message. Anchor your reply to what they have/haven\'t mastered.',
  );
  return lines.join('\n');
}
