/**
 * ncert-question-engine – Alfanumrik Edge Function
 *
 * Two actions:
 *
 * 1. fetch_questions
 *    Fetches NCERT questions from ncert_exercises + rag_content_chunks for a
 *    given subject/grade/chapter and question type (mcq|short_answer|medium_answer|
 *    long_answer|mixed).  Returns up to `count` deduplicated questions.
 *
 * 2. evaluate_answer
 *    Evaluates a student's written answer against the NCERT model answer
 *    retrieved from RAG. Returns marks, CBSE examiner feedback, and key points
 *    the student hit/missed.  Uses Claude (no Voyage needed for evaluation –
 *    model answer is fetched directly from DB by question_id).
 *
 * POST body for fetch_questions:
 * {
 *   action: 'fetch_questions',
 *   student_id: string,
 *   subject: string,     e.g. "science"
 *   grade: string,       e.g. "9" or "Grade 9"
 *   chapter: number,
 *   question_type: 'mcq'|'short_answer'|'medium_answer'|'long_answer'|'mixed'|'all',
 *   count?: number       default 10
 * }
 *
 * POST body for evaluate_answer:
 * {
 *   action: 'evaluate_answer',
 *   student_id: string,
 *   question_id: string (uuid),
 *   source_table: 'ncert_exercises'|'rag_content_chunks'|'question_bank',
 *   question_text: string,
 *   student_answer: string,
 *   marks_possible: number,
 *   question_type: string
 * }
 *
 * `question_bank` source covers two written-answer cohorts:
 *   • NCERT exercises promoted into question_bank (Phase 1, source='ncert_extracted_2026')
 *   • CBSE-style SA/LA questions generated by bulk-non-mcq-gen (Phase 2)
 * For both, the model answer lives in question_bank.expected_answer (preferred)
 * or answer_text, and the marking rubric (jsonb array of point/marks objects)
 * lives in question_bank.answer_rubric.
 *
 * POST body for save_attempt:
 * {
 *   action: 'save_attempt',
 *   student_id: string,
 *   question_id: string,
 *   source_table: string,
 *   subject: string,
 *   grade: string,
 *   chapter_number: number,
 *   question_type: string,
 *   marks_possible: number,
 *   student_answer?: string,
 *   selected_option?: number,
 *   marks_awarded: number,
 *   is_correct: boolean,
 *   ai_feedback?: string,
 *   ai_key_points?: {point: string, hit: boolean}[],
 *   model_answer?: string,
 *   time_spent?: number,
 *   session_id?: string
 * }
 */

function logDeprecatedEdgeFunctionHit() {
  console.warn('api_deprecated_edge_function_hit', { workflow: 'ncert-solve', route: 'supabase/functions/ncert-question-engine/index.ts', canonical_route: '/api/scan-solve', compatibility_type: 'internal-only', metric: 'api_deprecated_route_hit' })
}

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { jsonResponse, errorResponse } from '../_shared/cors.ts'
import { getRequestId, getRequestIp, getRequestOrigin, hashRequestIp } from '../_shared/security/attribution.ts'
import { resolveSecurityPrincipal } from '../_shared/security/auth.ts'
import { resolveRoutePolicy } from '../_shared/security/policy.ts'
import { computeEstimatedCost, reserveQuota, settleQuota } from '../_shared/security/quota.ts'
import { writeSecurityAudit } from '../_shared/security/audit.ts'
import { recordCircuitOutcome } from '../_shared/security/circuit.ts'
import { securityCorsHeaders, securityErrorResponse } from '../_shared/security/cors.ts'
import { sha256Hex } from '../_shared/security/request-signature.ts'
import type { SecurityPrincipal, SecurityQuotaEstimate } from '../_shared/security/types.ts'
import { createRateLimiter } from '../_shared/rate-limiter.ts'

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!
const SUPABASE_SERVICE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const ANTHROPIC_KEY = Deno.env.get('ANTHROPIC_API_KEY')!
const ROUTE_NAME = 'ncert-question-engine'

type SupabaseClient = ReturnType<typeof createClient>

type Admission = {
  requestId: string
  origin: string | null
  requestIpHash: string
  principal: SecurityPrincipal
  policyMode: 'enforce' | 'shadow' | 'observe' | 'disabled'
  quotaDecision: { allowed: boolean; decision: string; enforcementMode: 'enforce' | 'shadow' | 'observe' | 'disabled'; circuitState?: 'closed' | 'open' | 'half_open'; reason?: string }
  quotaEstimate: SecurityQuotaEstimate
}

function estimateTokens(text: string): number {
  return Math.max(1, Math.ceil(text.length / 4))
}

function estimateNcertUsage(body: Record<string, unknown>): SecurityQuotaEstimate {
  const action = String(body.action ?? '')
  if (action === 'evaluate_answer') {
    const promptBits = [
      body.question_text,
      body.student_answer,
      body.question_type,
      body.marks_possible,
    ].map((v) => String(v ?? '')).join('\n')
    return {
      requestCount: 1,
      estimatedInputTokens: estimateTokens(promptBits) + 700,
      estimatedOutputTokens: 600,
      estimatedCost: 0,
      modelProvider: 'anthropic',
      modelName: 'claude-haiku-4-5-20251001',
    }
  }
  return {
    requestCount: 1,
    estimatedInputTokens: 32,
    estimatedOutputTokens: 64,
    estimatedCost: 0,
    modelProvider: 'anthropic',
    modelName: 'claude-haiku-4-5-20251001',
  }
}

function normalizeQuotaDecision(input: { allowed?: boolean; decision?: string; enforcementMode?: 'enforce' | 'shadow' | 'observe' | 'disabled'; circuitState?: 'closed' | 'open' | 'half_open'; reason?: string }) {
  return {
    allowed: input.allowed === true,
    decision: input.decision ?? 'deny_invalid_request',
    enforcementMode: input.enforcementMode ?? 'enforce',
    circuitState: input.circuitState ?? 'closed',
    reason: input.reason,
  }
}

async function resolveAuthorizedStudentId(sb: SupabaseClient, principal: SecurityPrincipal, body: Record<string, unknown>): Promise<string | null> {
  if (principal.role === 'student' && principal.userId) {
    const { data } = await sb
      .from('students')
      .select('id')
      .eq('auth_user_id', principal.userId)
      .eq('is_active', true)
      .maybeSingle()
    return data?.id ? String(data.id) : null
  }

  const requestedStudentId = body.student_id ? String(body.student_id) : ''
  if (!requestedStudentId) return null

  if (principal.callerType === 'internal_service') {
    return requestedStudentId
  }

  if (!principal.userId || !principal.schoolId) return null

  if (principal.role === 'parent') {
    const { data } = await sb
      .from('guardian_student_links')
      .select('student_id, guardians!inner(auth_user_id), students!inner(school_id, is_active)')
      .eq('student_id', requestedStudentId)
      .eq('guardians.auth_user_id', principal.userId)
      .eq('students.school_id', principal.schoolId)
      .eq('students.is_active', true)
      .eq('status', 'active')
      .maybeSingle()
    return data?.student_id ? requestedStudentId : null
  }

  if (principal.role === 'teacher' || principal.role === 'school_admin') {
    const { data } = await sb
      .from('students')
      .select('id')
      .eq('id', requestedStudentId)
      .eq('school_id', principal.schoolId)
      .eq('is_active', true)
      .maybeSingle()
    return data?.id ? requestedStudentId : null
  }

  return null
}

async function finalizeSecurity(args: {
  sb: SupabaseClient
  admission: Admission
  started: number
  statusCode: number
  errorCode?: string | null
  actualInputTokens?: number | null
  actualOutputTokens?: number | null
  actualCost?: number | null
}) {
  const breakerState = args.admission.quotaDecision.circuitState ?? 'closed'
  try {
    await writeSecurityAudit(args.sb, {
      requestId: args.admission.requestId,
      route: ROUTE_NAME,
      schoolId: args.admission.principal.schoolId,
      userId: args.admission.principal.userId,
      role: args.admission.principal.role,
      callerType: args.admission.principal.callerType,
      serviceName: args.admission.principal.serviceName,
      cronJob: args.admission.principal.cronJob,
      internalWorker: args.admission.principal.internalWorker,
      internalCallerId: args.admission.principal.internalCallerId,
      quotaDecision: args.admission.policyMode === 'enforce' ? args.admission.quotaDecision.decision : `shadow_${args.admission.quotaDecision.decision}`,
      latencyMs: Date.now() - args.started,
      statusCode: args.statusCode,
      enforcementMode: args.admission.policyMode,
      breakerState,
      errorCode: args.errorCode ?? null,
      estimatedInputTokens: args.admission.quotaEstimate.estimatedInputTokens,
      estimatedOutputTokens: args.admission.quotaEstimate.estimatedOutputTokens,
      estimatedCost: args.admission.quotaEstimate.estimatedCost,
      actualInputTokens: args.actualInputTokens ?? null,
      actualOutputTokens: args.actualOutputTokens ?? null,
      actualCost: args.actualCost ?? null,
    })
  } catch (err) {
    console.error(`[ncert-question-engine] audit write failed: ${String(err instanceof Error ? err.message : err)}`)
  }
  if (args.statusCode < 400) {
    try {
      await settleQuota(args.sb, {
        route: ROUTE_NAME,
        principal: args.admission.principal,
        requestIpHash: args.admission.requestIpHash,
        actualInputTokens: args.actualInputTokens ?? args.admission.quotaEstimate.estimatedInputTokens,
        actualOutputTokens: args.actualOutputTokens ?? args.admission.quotaEstimate.estimatedOutputTokens,
        actualCost: args.actualCost ?? args.admission.quotaEstimate.estimatedCost,
        requestCount: 1,
      })
    } catch (err) {
      console.error(`[ncert-question-engine] quota settle failed: ${String(err instanceof Error ? err.message : err)}`)
    }
  }
  try {
    await recordCircuitOutcome(args.sb, {
      route: ROUTE_NAME,
      schoolId: args.admission.principal.schoolId,
      role: args.admission.principal.role,
      callerType: args.admission.principal.callerType,
      internalCallerId: args.admission.principal.internalCallerId,
      event: args.statusCode >= 500 ? 'failure' : 'success',
      errorCode: args.errorCode ?? null,
    })
  } catch (err) {
    console.error(`[ncert-question-engine] circuit update failed: ${String(err instanceof Error ? err.message : err)}`)
  }
}

// CBSE marks → question type mapping
const CBSE_TYPE_MAP: Record<string, { label: string; marksRange: [number, number]; timeSeconds: number; wordLimit: number }> = {
  mcq:           { label: 'MCQ',           marksRange: [1, 1],  timeSeconds: 60,  wordLimit: 0   },
  short_answer:  { label: 'Short Answer',  marksRange: [1, 2],  timeSeconds: 120, wordLimit: 40  },
  medium_answer: { label: 'Medium Answer', marksRange: [3, 4],  timeSeconds: 240, wordLimit: 100 },
  long_answer:   { label: 'Long Answer',   marksRange: [5, 6],  timeSeconds: 480, wordLimit: 200 },
  hots:          { label: 'HOTS',          marksRange: [4, 5],  timeSeconds: 360, wordLimit: 150 },
  numerical:     { label: 'Numerical',     marksRange: [2, 3],  timeSeconds: 180, wordLimit: 60  },
  intext:        { label: 'Intext',        marksRange: [1, 3],  timeSeconds: 150, wordLimit: 80  },
}

// ─── Helper: normalise grade string ──────────────────────────────────────────
function normaliseGrade(grade: string): string {
  return grade.replace(/^Grade\s*/i, '').trim()
}

// ─── Action: fetch_questions ──────────────────────────────────────────────────
async function fetchQuestions(body: Record<string, unknown>): Promise<Response> {
  const origin = body._origin as string | undefined
  const { student_id, subject, grade, chapter, question_type = 'all', count = 10 } = body as {
    student_id: string; subject: string; grade: string; chapter: number;
    question_type?: string; count?: number
  }

  if (!student_id || !subject || !grade || !chapter) {
    return errorResponse('student_id, subject, grade, chapter are required', 400, origin)
  }

  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY)

  // Fetch previously seen NCERT question IDs for this student (30-day window)
  const seenIds = new Set<string>()
  try {
    const thirtyDaysAgo = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()
    const { data: attempts } = await supabase
      .from('student_ncert_attempts')
      .select('question_id')
      .eq('student_id', student_id)
      .gte('created_at', thirtyDaysAgo)
      .not('question_id', 'is', null)
    if (attempts) {
      for (const row of attempts) {
        if (row.question_id) seenIds.add(row.question_id)
      }
    }
    // Also check user_question_history for unified tracking
    const { data: historyRows } = await supabase
      .from('user_question_history')
      .select('question_id')
      .eq('student_id', student_id)
      .eq('subject', subject)
      .limit(500)
    if (historyRows) {
      for (const row of historyRows) {
        if (row.question_id) seenIds.add(row.question_id)
      }
    }
  } catch {
    // Non-fatal: proceed without exclusion
  }

  // Resolve "mixed" into multiple types
  const typeParam = question_type === 'mixed' ? 'all' : question_type

  const { data: rows, error } = await supabase.rpc('get_ncert_questions', {
    p_subject: subject,
    p_grade: grade,
    p_chapter: chapter,
    p_question_type: typeParam,
    p_limit: Math.min(count * 3, 90), // fetch extra for dedup + seen exclusion
  })

  if (error) {
    console.error('get_ncert_questions error:', error)
    return errorResponse('Failed to fetch NCERT questions', 500, origin)
  }

  // Dedup by question_text prefix (first 80 chars)
  const seen = new Set<string>()
  const deduped = (rows ?? []).filter((q: Record<string, unknown>) => {
    const key = String(q.question_text ?? '').slice(0, 80).toLowerCase().trim()
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })

  // Separate into unseen and previously seen questions
  const unseenQuestions = deduped.filter((q: Record<string, unknown>) => !seenIds.has(String(q.id)))
  const previouslySeen = deduped.filter((q: Record<string, unknown>) => seenIds.has(String(q.id)))

  // For mixed mode, enforce CBSE paper balance: ~40% MCQ, ~30% SA, ~20% MA, ~10% LA
  // Apply balance to unseen first, then backfill from seen if pool exhausted
  const applyBalance = (pool: Record<string, unknown>[], targetCount: number): Record<string, unknown>[] => {
    const mcq = pool.filter((q) => q.question_type === 'mcq')
    const sa  = pool.filter((q) => ['short_answer','intext'].includes(String(q.question_type)) && Number(q.marks_possible) <= 2)
    const ma  = pool.filter((q) => Number(q.marks_possible) >= 3 && Number(q.marks_possible) <= 4)
    const la  = pool.filter((q) => Number(q.marks_possible) >= 5 || ['long_answer','hots'].includes(String(q.question_type)))
    const n   = Math.max(targetCount, 10)
    return [
      ...mcq.slice(0, Math.ceil(n * 0.4)),
      ...sa.slice(0,  Math.ceil(n * 0.3)),
      ...ma.slice(0,  Math.ceil(n * 0.2)),
      ...la.slice(0,  Math.ceil(n * 0.1)),
    ].slice(0, targetCount)
  }

  let selected: Record<string, unknown>[]
  if (question_type === 'mixed') {
    // Try unseen first, backfill with seen if needed
    selected = applyBalance(unseenQuestions, count)
    if (selected.length < count) {
      const remaining = count - selected.length
      const backfill = applyBalance(previouslySeen, remaining)
      selected = [...selected, ...backfill]
    }
  } else {
    // Prioritize unseen, then backfill with seen
    selected = [...unseenQuestions, ...previouslySeen].slice(0, count)
  }

  // Enrich with CBSE metadata
  const enriched = selected.map((q: Record<string, unknown>) => {
    const qt = String(q.question_type ?? 'short_answer')
    const marks = Number(q.marks_possible ?? 1)
    let cbseType = qt
    if (qt === 'intext' || (qt === 'short_answer' && marks <= 2)) cbseType = 'short_answer'
    else if (qt === 'short_answer' && marks >= 3)                  cbseType = 'medium_answer'
    else if (qt === 'long_answer')                                  cbseType = 'long_answer'
    const meta = CBSE_TYPE_MAP[cbseType] ?? CBSE_TYPE_MAP.short_answer
    return { ...q, cbse_type: cbseType, cbse_label: meta.label, time_estimate: meta.timeSeconds, word_limit: meta.wordLimit }
  })

  return jsonResponse({ questions: enriched, total: enriched.length, chapter, subject, grade }, 200, {}, origin)
}

// ─── Rate limiter: evaluate_answer (Anthropic call, most expensive path) ─────
// 30 evaluations per student per 10-minute window stored in Supabase KV via
// a simple counter row in student_ncert_attempts aggregation.
// Uses a lightweight in-memory store keyed by student_id for the current
// Edge Function instance. At scale, use Upstash Redis or Supabase realtime.
const EVAL_LIMIT = 30
const EVAL_WINDOW_MS = 10 * 60 * 1000 // 10 minutes

const checkEvalRateLimit = createRateLimiter(EVAL_LIMIT, EVAL_WINDOW_MS)

// ─── Action: evaluate_answer ──────────────────────────────────────────────────
async function evaluateAnswer(body: Record<string, unknown>): Promise<Response> {
  const origin = body._origin as string | undefined
  const {
    student_id, question_id, source_table, question_text,
    student_answer, marks_possible, question_type
  } = body as {
    student_id: string; question_id: string; source_table: string;
    question_text: string; student_answer: string;
    marks_possible: number; question_type: string
  }

  if (!student_id || !question_id || !student_answer || !question_text) {
    return errorResponse('student_id, question_id, question_text, student_answer required', 400, origin)
  }
  if (!marks_possible || marks_possible < 1) {
    return errorResponse('marks_possible must be >= 1', 400, origin)
  }

  // Rate limit: 30 evaluations / 10 min per student (Anthropic cost protection)
  const rl = checkEvalRateLimit(student_id)
  if (!rl.allowed) {
    const retryAfterSec = Math.ceil(rl.retryAfterMs / 1000)
    return new Response(
      JSON.stringify({ error: 'Too many evaluation requests. Please wait before submitting more answers.', retry_after_seconds: retryAfterSec }),
      { status: 429, headers: { 'Content-Type': 'application/json', 'Retry-After': String(retryAfterSec), ...(origin ? { 'Access-Control-Allow-Origin': origin } : {}) } }
    )
  }

  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY)

  // Fetch model answer + rubric from source table
  let modelAnswer = ''
  let solutionSteps = ''
  let rubricPoints: Array<{ point: string; marks: number }> = []
  if (source_table === 'ncert_exercises') {
    const { data } = await supabase.from('ncert_exercises').select('answer_text, solution_steps').eq('id', question_id).single()
    modelAnswer   = data?.answer_text ?? ''
    solutionSteps = data?.solution_steps ?? ''
  } else if (source_table === 'question_bank') {
    // Bulk-generated SA/LA + promoted NCERT-into-question_bank rows. The
    // model answer lives in expected_answer (preferred) or answer_text, and
    // a structured rubric lives in answer_rubric jsonb.
    const { data } = await supabase
      .from('question_bank')
      .select('expected_answer, answer_text, explanation, answer_rubric')
      .eq('id', question_id)
      .single()
    modelAnswer = data?.expected_answer || data?.answer_text || ''
    solutionSteps = data?.explanation ?? ''
    // answer_rubric is stored in TWO shapes:
    //   • bulk-non-mcq-gen (Phase 2, ~92% of rows): an OBJECT { points: [{point, marks}] }
    //   • promoted/legacy NCERT rows (~8%): a bare ARRAY [{point, marks}]
    // Unwrap both into a single array before mapping so the per-mark CBSE
    // scheme reaches the examiner prompt in either case.
    const rawRubric = data?.answer_rubric as unknown
    const rubric = Array.isArray(rawRubric)
      ? rawRubric
      : (rawRubric && typeof rawRubric === 'object'
          ? ((rawRubric as Record<string, unknown>).points as unknown)
          : null)
    if (Array.isArray(rubric)) {
      rubricPoints = (rubric as Array<Record<string, unknown>>)
        .map((r) => ({
          point: String(r.point ?? r.criterion ?? ''),
          marks: Number(r.marks ?? r.points ?? 0),
        }))
        .filter((r) => r.point.length > 0)
    }
  } else {
    const { data } = await supabase.from('rag_content_chunks').select('answer_text, chunk_text').eq('id', question_id).single()
    modelAnswer = data?.answer_text ?? data?.chunk_text ?? ''
  }

  // If no model answer in DB, use RAG to retrieve context
  if (!modelAnswer) {
    const { data: ragData } = await supabase
      .from('rag_content_chunks')
      .select('chunk_text')
      .ilike('question_text', `%${question_text.slice(0, 40)}%`)
      .limit(2)
    modelAnswer = (ragData ?? []).map((r: Record<string, string>) => r.chunk_text).join('\n')
  }

  // Build CBSE examiner prompt
  const cbseMeta = CBSE_TYPE_MAP[question_type] ?? CBSE_TYPE_MAP.short_answer
  const marksLabel = marks_possible === 1 ? '1 mark' : `${marks_possible} marks`

  // When the source table provides a structured rubric (question_bank rows),
  // surface it to Claude so the breakdown is faithful to the marking scheme
  // and total marks add up. Otherwise the examiner derives key points itself.
  const rubricBlock = rubricPoints.length > 0
    ? `\nMARKING RUBRIC (sum of marks = ${marks_possible}):\n${rubricPoints.map((r, i) => `${i + 1}. [${r.marks} mark${r.marks === 1 ? '' : 's'}] ${r.point}`).join('\n')}\n`
    : ''

  const evalPrompt = `You are a strict but fair CBSE examiner evaluating a student's answer.

QUESTION (${cbseMeta.label}, ${marksLabel}):
${question_text}

MODEL ANSWER / KEY CONTENT:
${modelAnswer}
${solutionSteps ? `\nSOLUTION STEPS:\n${solutionSteps}` : ''}${rubricBlock}
STUDENT'S ANSWER:
${student_answer}

CBSE MARKING RULES:
- Total marks: ${marks_possible}
- Award full marks only if ALL key points are present
- Partial marks for partially correct answers (round to nearest 0.5)
- Deduct 0 marks for spelling mistakes unless it changes meaning
- Award 0 for irrelevant/blank answers
- For ${cbseMeta.label}: expected ~${cbseMeta.wordLimit} words${rubricPoints.length > 0 ? '\n- Use the MARKING RUBRIC above: each rubric line is worth its stated marks; partial credit is allowed within a line.' : ''}

EVALUATE and respond in this EXACT JSON format (no extra text):
{
  "marks_awarded": <integer 0 to ${marks_possible}>,
  "percentage": <0-100>,
  "feedback": "<2-3 sentences: what was correct, what was missing, how to improve>",
  "key_points": [
    {"point": "<key concept from model answer>", "hit": true/false},
    ...
  ],
  "model_answer_summary": "<concise 1-3 sentence model answer suitable for a student to learn from>",
  "grade": "<Excellent|Good|Satisfactory|Needs Improvement>"
}`

  // eslint-disable-next-line alfanumrik/no-direct-ai-calls -- TODO(phase-4-cleanup): ncert-question-engine grades answers; route through grounded-answer when a grading-specific template is available.
  const aiResp = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': ANTHROPIC_KEY,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 600,
      messages: [{ role: 'user', content: evalPrompt }],
    }),
  })

  if (!aiResp.ok) {
    console.error('Anthropic eval error:', await aiResp.text())
    // Fallback: rough word-match scoring
    const wordMatch = roughWordMatch(student_answer, modelAnswer, marks_possible)
    return jsonResponse(wordMatch, 200, {}, origin)
  }

  const aiData = await aiResp.json()
  const rawText = aiData.content?.[0]?.text ?? '{}'

  let parsed: Record<string, unknown>
  try {
    parsed = JSON.parse(rawText)
  } catch {
    // Try to extract JSON from response
    const jsonMatch = rawText.match(/\{[\s\S]*\}/)
    try { parsed = JSON.parse(jsonMatch?.[0] ?? '{}') } catch { parsed = {} }
  }

  const result = {
    marks_awarded:          Math.min(Math.max(0, Math.round(Number(parsed.marks_awarded ?? 0))), marks_possible),
    marks_possible,
    percentage:             Number(parsed.percentage ?? 0),
    feedback:               String(parsed.feedback ?? 'Please review the model answer.'),
    key_points:             Array.isArray(parsed.key_points) ? parsed.key_points : [],
    model_answer_summary:   String(parsed.model_answer_summary ?? modelAnswer.slice(0, 300)),
    grade:                  String(parsed.grade ?? 'Needs Improvement'),
    is_correct:             Number(parsed.marks_awarded ?? 0) >= marks_possible,
  }

  return jsonResponse(result, 200, {}, origin)
}

// ─── Fallback: rough word match scoring ──────────────────────────────────────
function roughWordMatch(studentAnswer: string, modelAnswer: string, maxMarks: number) {
  const studentWords = new Set(studentAnswer.toLowerCase().split(/\W+/).filter(w => w.length > 3))
  const modelWords   = modelAnswer.toLowerCase().split(/\W+/).filter(w => w.length > 3)
  const keyWords     = modelWords.slice(0, 20)
  const hits         = keyWords.filter(w => studentWords.has(w)).length
  const ratio        = keyWords.length > 0 ? hits / keyWords.length : 0
  const marks        = Math.round(ratio * maxMarks)
  return {
    marks_awarded: marks, marks_possible: maxMarks, percentage: Math.round(ratio * 100),
    feedback: 'Answer evaluated. Review the model answer to see key points.',
    key_points: keyWords.slice(0, 5).map(w => ({ point: w, hit: studentWords.has(w) })),
    model_answer_summary: modelAnswer.slice(0, 300),
    grade: ratio >= 0.8 ? 'Good' : ratio >= 0.5 ? 'Satisfactory' : 'Needs Improvement',
    is_correct: marks >= maxMarks,
  }
}

// ─── Action: save_attempt ────────────────────────────────────────────────────
async function saveAttempt(body: Record<string, unknown>): Promise<Response> {
  const origin = body._origin as string | undefined
  const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY)

  const row = {
    student_id:     body.student_id,
    source_table:   body.source_table,
    question_id:    body.question_id,
    subject:        body.subject,
    grade:          normaliseGrade(String(body.grade ?? '')),
    chapter_number: body.chapter_number,
    question_type:  body.question_type,
    marks_possible: body.marks_possible,
    student_answer: body.student_answer ?? null,
    selected_option: body.selected_option ?? null,
    marks_awarded:  body.marks_awarded,
    is_correct:     body.is_correct,
    ai_feedback:    body.ai_feedback ?? null,
    ai_key_points:  body.ai_key_points ?? [],
    model_answer:   body.model_answer ?? null,
    time_spent:     body.time_spent ?? null,
    session_id:     body.session_id ?? null,
  }

  const { data, error } = await supabase.from('student_ncert_attempts').insert(row).select('id').single()
  if (error) {
    console.error('save_attempt error:', error)
    return errorResponse('Failed to save attempt', 500, origin)
  }
  return jsonResponse({ id: data.id, saved: true }, 200, {}, origin)
}

// ─── Main handler ─────────────────────────────────────────────────────────────
export async function handleRequest(req: Request): Promise<Response> {
  logDeprecatedEdgeFunctionHit()
  const started = Date.now()
  const origin = getRequestOrigin(req)
  const corsH = securityCorsHeaders(origin)

  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: corsH })
  }

  if (req.method !== 'POST') {
    return new Response('Method not allowed', { status: 405, headers: corsH })
  }

  const requestId = getRequestId(req)
  const ipAddress = getRequestIp(req)
  const requestIpHash = await hashRequestIp(ipAddress, Deno.env.get('SECURITY_IP_HASH_SALT') ?? '')

  let rawBody = ''
  try {
    rawBody = await req.text()
  } catch {
    return securityErrorResponse('invalid_body', 'failed to read request body', 400, origin, requestId)
  }

  const bodyHash = await sha256Hex(rawBody)
  let body: Record<string, unknown>
  try {
    body = rawBody ? JSON.parse(rawBody) : {}
    body._origin = origin
  } catch {
    return securityErrorResponse('invalid_json', 'Invalid JSON body', 400, origin, requestId)
  }

  const sb = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY)
  const principalRes = await resolveSecurityPrincipal({
    req,
    sb,
    _route: ROUTE_NAME,
    requestId,
    bodyHash,
    requestBodyCaller: String(body.caller ?? 'ncert-question-engine'),
  })
  if (!principalRes.ok) {
    return securityErrorResponse(principalRes.code, principalRes.message, principalRes.status, origin, requestId)
  }

  const principal = principalRes.principal
  const policy = await resolveRoutePolicy(sb, {
    route: ROUTE_NAME,
    schoolId: principal.schoolId,
    role: principal.role,
    callerType: principal.callerType,
    internalCallerId: principal.internalCallerId,
  })
  if (!policy || !policy.isEnabled) {
    return securityErrorResponse('deny_policy', policy ? 'route policy is disabled' : 'route policy not found', 403, origin, requestId)
  }
  if (principal.callerType === 'internal_service' ? !policy.allowSignedInternal : !policy.allowJwt) {
    return securityErrorResponse('deny_policy', 'caller is not permitted on this route', 403, origin, requestId)
  }

  const resolvedStudentId = await resolveAuthorizedStudentId(sb, principal, body)
  if (!resolvedStudentId) {
    return securityErrorResponse('deny_auth', 'No active or authorized student profile for this request', 403, origin, requestId)
  }
  body.student_id = resolvedStudentId

  const quotaEstimate = estimateNcertUsage(body)
  quotaEstimate.estimatedCost = await computeEstimatedCost(sb, quotaEstimate)
  const quotaDecision = normalizeQuotaDecision(await reserveQuota(sb, {
    route: ROUTE_NAME,
    principal,
    _requestId: requestId,
    requestIpHash,
    estimate: quotaEstimate,
    dryRun: policy.enforcementMode !== 'enforce',
  }))
  if (policy.enforcementMode === 'enforce' && !quotaDecision.allowed) {
    return securityErrorResponse(
      quotaDecision.decision,
      quotaDecision.reason ?? 'quota denied',
      quotaDecision.decision === 'deny_breaker' ? 503 : 429,
      origin,
      requestId,
    )
  }

  const admission: Admission = { requestId, origin, requestIpHash, principal, policyMode: policy.enforcementMode, quotaDecision, quotaEstimate }
  const action = String(body.action ?? '')
  let response: Response
  try {
    switch (action) {
      case 'fetch_questions': response = await fetchQuestions(body); break
      case 'evaluate_answer': response = await evaluateAnswer(body); break
      case 'save_attempt':    response = await saveAttempt(body); break
      default:
        response = errorResponse(`Unknown action "${action}". Valid: fetch_questions, evaluate_answer, save_attempt`, 400, origin)
    }
  } catch (err) {
    console.error(`[ncert-question-engine] unhandled error: ${String(err instanceof Error ? err.stack ?? err.message : err)}`)
    response = securityErrorResponse('internal_error', 'Internal server error', 500, origin, requestId)
  }

  await finalizeSecurity({
    sb,
    admission,
    started,
    statusCode: response.status,
    errorCode: response.status >= 400 ? (response.status >= 500 ? 'internal_error' : 'request_error') : null,
  })
  return response
}

Deno.serve(handleRequest)
