# ── Stage 1: Install dependencies ───────────────────────────────────────────
FROM node:20-alpine AS deps
# libc6-compat for native modules (e.g. sharp)
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json ./
# Install ALL deps (devDeps needed for build)
RUN npm ci

# ── Stage 2: Build ──────────────────────────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# NEXT_PUBLIC_* vars are baked into the client bundle at build time.
# Server-only secrets (Supabase service role, Razorpay, etc.) are NOT
# passed here — they are injected by ECS at task start via Secrets Manager.
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_SENTRY_DSN
ARG NEXT_PUBLIC_POSTHOG_KEY
ARG NEXT_PUBLIC_POSTHOG_HOST
ARG NEXT_PUBLIC_POSTHOG_ENABLED

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN
ENV NEXT_PUBLIC_POSTHOG_KEY=$NEXT_PUBLIC_POSTHOG_KEY
ENV NEXT_PUBLIC_POSTHOG_HOST=$NEXT_PUBLIC_POSTHOG_HOST
ENV NEXT_PUBLIC_POSTHOG_ENABLED=$NEXT_PUBLIC_POSTHOG_ENABLED

# NODE_ENV=production triggers Next.js optimisations.
# Do NOT set DEPLOY_TARGET here — that is a runtime flag (injected by ECS
# task definition); setting it at build time would trigger env validation
# before server secrets are present, causing the build to fail.
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Bump Node.js heap for Next.js build — mirrors NODE_OPTIONS in ci.yml and
# deploy-production.yml. Without this, `next build` hits the V8 default
# ~1.5 GB heap limit and exits SIGABRT inside Docker. See PR #818 for history.
ENV NODE_OPTIONS="--max-old-space-size=6144"

RUN npm run build

# ── Stage 3: Production runner ───────────────────────────────────────────────
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Run as non-root (security best practice)
RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 nextjs

# Copy the standalone output — self-contained Node server
COPY --from=builder /app/apps/host/public ./apps/host/public
COPY --from=builder --chown=nextjs:nodejs /app/apps/host/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/host/.next/static ./apps/host/.next/static

USER nextjs

EXPOSE 3000

# server.js is generated by Next.js standalone output
# Liveness probe  uses node (not curl) since alpine may not have curl installed.
# ECS target-group health checks /api/v1/health separately; this adds Docker-native
# container health visibility (e.g. in ECS service events, docker ps).
HEALTHCHECK --interval=60s --timeout=5s --start-period=60s --retries=3 CMD node -e "require('http').get('http://localhost:3000/api/v1/health', r => process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))"

CMD ["node", "apps/host/server.js"]
