import { supabaseAdmin } from '@alfanumrik/lib/supabase-admin';
import { validateCandidate } from '@alfanumrik/lib/ai/validation/quiz-oracle';
import { logger } from '@alfanumrik/lib/logger';
import type { ToolDefinition } from '@alfanumrik/lib/ai/agents/types';
import type { FixStrategy, RegenCandidate } from '@alfanumrik/lib/qb-fixer/types';
import { hashCandidate } from './re-verify';

interface CommitInput {
  question_id: string;
  fixed_question: RegenCandidate;
  /**
   * NOTE: 'full_regen' is overloaded. Besides its literal meaning (content was
   * actually regenerated by regenerate_question), the agent's system prompt
   * (../system-prompt.ts) also reuses it as a bookkeeping label for the
   * "re-verified unchanged, nothing regenerated" outcome of the
   * retry-on-'chapter_not_ready' path: when a chapter_not_ready abstain is
   * retried and the SAME original candidate re-verifies successfully,
   * commit_fix is called with that unchanged candidate and
   * fix_strategy='full_regen', even though nothing was regenerated. This is
   * because question_bank_fix_history.fix_strategy's CHECK constraint
   * (supabase/migrations/20260510064952_qb_fixer.sql) has no dedicated value
   * for "reverify confirmed, no change" — adding one (e.g. a
   * 'reverify_confirmed' value via a small additive migration) is a tracked
   * follow-up, not done here. See the matching note on FixStrategy in
   * ../../../../qb-fixer/types.ts.
   */
  fix_strategy: FixStrategy;
}

export const commitFixTool: ToolDefinition<CommitInput, { ok: true }> = {
  name: 'commit_fix',
  description:
    'Commit a verified candidate to question_bank. PRECONDITION: a successful re_verify must have stamped ctx.meta with verified_<question_id>_<hash> for THIS candidate. Also enforces validateCandidate (P11 oracle).',
  inputSchema: {
    type: 'object',
    properties: {
      question_id: { type: 'string' },
      fixed_question: {
        type: 'object',
        properties: {
          question: { type: 'string' },
          options: { type: 'array', items: { type: 'string' }, minItems: 4, maxItems: 4 },
          correct_answer_index: { type: 'integer', minimum: 0, maximum: 3 },
          explanation: { type: 'string' },
        },
        required: ['question', 'options', 'correct_answer_index', 'explanation'],
      },
      fix_strategy: {
        type: 'string',
        // 'full_regen' is also reused as a bookkeeping-only value for the
        // "reverified unchanged" outcome — see the note on CommitInput above.
        enum: ['index_correction', 'explanation_only', 'full_regen'],
      },
    },
    required: ['question_id', 'fixed_question', 'fix_strategy'],
  },
  handler: async (input, ctx) => {
    // Precondition 1: matching re_verify success in ctx.meta
    const expectedKey = `verified_${input.question_id}_${hashCandidate(input.fixed_question)}`;
    if (ctx.meta[expectedKey] !== true) {
      throw new Error(`commit_fix precondition failed: no re_verify success recorded for ${input.question_id} with this candidate`);
    }

    // Precondition 2: P11 structural oracle
    const validation = await validateCandidate(
      {
        question_text: input.fixed_question.question,
        options: input.fixed_question.options,
        correct_answer_index: input.fixed_question.correct_answer_index,
        explanation: input.fixed_question.explanation,
      },
      { enableLlmGrader: false },
    );
    if (!validation.ok) {
      throw new Error(`commit_fix oracle rejected: ${validation.category} — ${validation.reason}`);
    }

    // Read prior values for history (including verifier_failure_reason directly
    // from question_bank). `is_verified` is read for the tier rule below, NOT
    // for history.
    const { data: prior, error: priorErr } = await supabaseAdmin
      .from('question_bank')
      .select('question_text, options, correct_answer_index, explanation, verifier_failure_reason, is_verified')
      .eq('id', input.question_id)
      .single();
    if (priorErr || !prior) {
      throw new Error(`commit_fix: failed to read prior row: ${priorErr?.message}`);
    }
    type Prior = {
      question_text: string;
      options: string[];
      correct_answer_index: number;
      explanation: string | null;
      verifier_failure_reason: string | null;
      is_verified: boolean | null;
    };
    const p = prior as Prior;

    // ── Tiered-verification rule (Decision A option 3, 2026-08-14) ──────────
    //
    // Two independent columns, two independent meanings — this agent writes
    // exactly one of them and must never blur them:
    //   verification_state / verified_against_ncert — AUTOMATED agent proof.
    //     Gates the PRACTICE / daily-quiz tier (get_quiz_questions,
    //     select_quiz_questions_rag/_v2 Tier-0 floor, migration
    //     20260814000014).
    //   is_verified — HUMAN SME sign-off, set only by
    //     POST /api/super-admin/questions/verify. Gates the EXAM tier
    //     (start_mock_test_attempt, migration 20260722097000) and is counted
    //     as `exam_ready_count` by the chapter picker.
    //
    // So this agent deliberately does NOT grant `is_verified`: an AI repair
    // earns practice serving, never exam eligibility. That divergence is the
    // design, not a bug — do not "fix" it by adding is_verified: true here.
    //
    // But the reverse case is a real integrity hole and IS handled: if a human
    // had signed this row off and we are now REWRITING its content, that
    // sign-off no longer describes what the row contains. Leaving it set would
    // let AI-rewritten text ride a stale human approval straight into a mock
    // test — precisely the failure the tiering exists to prevent. So when the
    // committed candidate differs from what the SME approved, the sign-off is
    // withdrawn and the row drops back to the practice tier until a human
    // re-verifies it.
    //
    // Only ever REMOVES exam eligibility; never grants it. When nothing
    // changed (the 're-verified unchanged' path — see the note on CommitInput)
    // the column is left untouched.
    const priorOptions = Array.isArray(p.options) ? p.options : [];
    const contentChanged =
      p.question_text !== input.fixed_question.question ||
      p.correct_answer_index !== input.fixed_question.correct_answer_index ||
      (p.explanation ?? '') !== input.fixed_question.explanation ||
      priorOptions.length !== input.fixed_question.options.length ||
      priorOptions.some((opt, i) => opt !== input.fixed_question.options[i]);
    const withdrawSmeSignOff = contentChanged && p.is_verified === true;

    // UPDATE the row
    const { error: updateErr } = await supabaseAdmin
      .from('question_bank')
      .update({
        question_text: input.fixed_question.question,
        options: input.fixed_question.options,
        correct_answer_index: input.fixed_question.correct_answer_index,
        explanation: input.fixed_question.explanation,
        verification_state: 'verified',
        verified_against_ncert: true,
        verification_claimed_by: null,
        verification_claim_expires_at: null,
        // Present only when withdrawing — an unconditional `is_verified: false`
        // would silently strip sign-off from rows this agent merely re-verified.
        ...(withdrawSmeSignOff ? { is_verified: false } : {}),
        updated_at: new Date().toISOString(),
      })
      .eq('id', input.question_id);
    if (updateErr) {
      throw new Error(`commit_fix UPDATE failed: ${updateErr.message}`);
    }

    if (withdrawSmeSignOff) {
      // Metadata only — ids and a reason, never question text (P13).
      logger.warn('commit_fix withdrew stale SME sign-off', {
        questionId: input.question_id,
        fixStrategy: input.fix_strategy,
        reason: 'content_rewritten_after_human_verification',
      });
    }

    // INSERT history row
    const { error: insertErr } = await supabaseAdmin.from('question_bank_fix_history').insert({
      question_id: input.question_id,
      agent_run_id: (ctx.meta.run_id as string | undefined) ?? null,
      fix_strategy: input.fix_strategy,
      prior_question_text: p.question_text,
      prior_options: p.options,
      prior_correct_answer_index: p.correct_answer_index,
      prior_explanation: p.explanation,
      prior_verifier_reason: p.verifier_failure_reason,
      outcome: 'verified',
      attempts: (ctx.meta.regen_attempts as number | undefined) ?? 1,
    });
    if (insertErr) {
      logger.warn('commit_fix history insert failed', { error: insertErr.message });
    }

    return { ok: true };
  },
  redactInTrace: (input, output) => ({ input, output }),
};
