'use client';

import dynamic from 'next/dynamic';

export interface BuiltInSimulation {
  id: string;
  title: string;
  description: string;
  subject: string;
  grade: string[];
  thumbnailEmoji: string;
  difficulty: number;
  bloomLevel: string;
  estimatedTimeMinutes: number;
  conceptTags: string[];
  foxyTip: string;
  component: React.ComponentType;
}

const OhmsLaw = dynamic(() => import('./OhmsLaw'), { ssr: false });
const PendulumLab = dynamic(() => import('./PendulumLab'), { ssr: false });
const LensRayDiagram = dynamic(() => import('./LensRayDiagram'), { ssr: false });
const WaveOnString = dynamic(() => import('./WaveOnString'), { ssr: false });
const ProjectileMotion = dynamic(() => import('./ProjectileMotion'), { ssr: false });
const PHScale = dynamic(() => import('./PHScale'), { ssr: false });
const PythagorasTheorem = dynamic(() => import('./PythagorasTheorem'), { ssr: false });
const FractionVisualizer = dynamic(() => import('./FractionVisualizer'), { ssr: false });
const TrigCircle = dynamic(() => import('./TrigCircle'), { ssr: false });
const NewtonLaws = dynamic(() => import('./NewtonLaws'), { ssr: false });
const BohrModel = dynamic(() => import('./BohrModel'), { ssr: false });
const QuadraticGraph = dynamic(() => import('./QuadraticGraph'), { ssr: false });
const HookesLaw = dynamic(() => import('./HookesLaw'), { ssr: false });
const LinearGraph = dynamic(() => import('./LinearGraph'), { ssr: false });
const ChemicalBalancer = dynamic(() => import('./ChemicalBalancer'), { ssr: false });
const GasLaws = dynamic(() => import('./GasLaws'), { ssr: false });
const ProbabilityLab = dynamic(() => import('./ProbabilityLab'), { ssr: false });
const SnellsLaw = dynamic(() => import('./SnellsLaw'), { ssr: false });
const IntegrationVisualizer = dynamic(() => import('./IntegrationVisualizer'), { ssr: false });

export const BUILT_IN_SIMULATIONS: BuiltInSimulation[] = [
  {
    id: 'builtin-ohms-law',
    title: "Ohm's Law Circuit Lab",
    description: 'Build a circuit and watch electrons flow! Change voltage and resistance to see how current changes in real-time.',
    subject: 'physics',
    grade: ['10', '11', '12'],
    thumbnailEmoji: '⚡',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 8,
    conceptTags: ['Electricity', "Ohm's Law", 'Current', 'Voltage', 'Resistance'],
    foxyTip: 'Try setting resistance very low — what happens to the current? This is why short circuits are dangerous!',
    component: OhmsLaw,
  },
  {
    id: 'builtin-pendulum',
    title: 'Pendulum Physics Lab',
    description: 'Swing a pendulum and discover what controls its period. Change gravity, length, and angle — which one matters most?',
    subject: 'physics',
    grade: ['9', '10', '11'],
    thumbnailEmoji: '🕐',
    difficulty: 2,
    bloomLevel: 'analyze',
    estimatedTimeMinutes: 10,
    conceptTags: ['Oscillation', 'Pendulum', 'Period', 'Gravity', 'SHM'],
    foxyTip: 'Does changing the angle change the period? Try it! The answer might surprise you for small angles.',
    component: PendulumLab,
  },
  {
    id: 'builtin-lens-ray',
    title: 'Lens & Mirror Ray Diagrams',
    description: 'Drag an object near a lens and watch the image form! See exactly how light bends through convex and concave lenses.',
    subject: 'physics',
    grade: ['10', '11', '12'],
    thumbnailEmoji: '🔍',
    difficulty: 3,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 12,
    conceptTags: ['Light', 'Refraction', 'Lens', 'Image Formation', 'Ray Diagram'],
    foxyTip: 'Move the object between F and 2F — this is the most asked case in board exams! Note if image is real or virtual.',
    component: LensRayDiagram,
  },
  {
    id: 'builtin-wave',
    title: 'Wave on a String',
    description: 'Create waves and see how frequency, amplitude, and speed are connected. Toggle standing waves to see nodes glow!',
    subject: 'physics',
    grade: ['9', '10', '11'],
    thumbnailEmoji: '🌊',
    difficulty: 2,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 8,
    conceptTags: ['Waves', 'Frequency', 'Amplitude', 'Wavelength', 'Standing Waves'],
    foxyTip: 'Watch the particles — they move up and down, not sideways! That\'s what makes it a transverse wave.',
    component: WaveOnString,
  },
  {
    id: 'builtin-projectile',
    title: 'Projectile Motion Launcher',
    description: 'Launch projectiles at different angles and speeds! Discover which angle gives maximum range and trace beautiful parabolas.',
    subject: 'physics',
    grade: ['11', '12'],
    thumbnailEmoji: '🚀',
    difficulty: 3,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 10,
    conceptTags: ['Projectile', 'Kinematics', 'Parabola', 'Range', 'Trajectory'],
    foxyTip: 'Try 45° for maximum range! Then try 30° and 60° — notice anything special about their ranges?',
    component: ProjectileMotion,
  },
  {
    id: 'builtin-ph-scale',
    title: 'pH Scale Explorer',
    description: 'Click everyday substances and watch the pH meter react! See litmus paper change color and learn acids from bases.',
    subject: 'chemistry',
    grade: ['7', '8', '9', '10'],
    thumbnailEmoji: '🧪',
    difficulty: 1,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 6,
    conceptTags: ['pH', 'Acids', 'Bases', 'Indicators', 'Litmus'],
    foxyTip: 'Your stomach acid has pH ~1.5! How does your body handle something so acidic?',
    component: PHScale,
  },
  {
    id: 'builtin-pythagoras',
    title: 'Pythagoras Theorem Explorer',
    description: 'Drag the triangle corners and watch the squares on each side change. See a² + b² = c² come alive!',
    subject: 'math',
    grade: ['8', '9', '10'],
    thumbnailEmoji: '📐',
    difficulty: 2,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 8,
    conceptTags: ['Pythagoras', 'Right Triangle', 'Geometry', 'Proof'],
    foxyTip: 'Try the 3-4-5 triangle — the simplest Pythagorean triple! Can you find others?',
    component: PythagorasTheorem,
  },
  {
    id: 'builtin-fractions',
    title: 'Pizza Fraction Lab',
    description: 'Slice pizzas into fractions! Compare halves, thirds, and quarters visually. Finally understand why 1/3 + 1/4 is not 2/7!',
    subject: 'math',
    grade: ['6', '7', '8'],
    thumbnailEmoji: '🍕',
    difficulty: 1,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 7,
    conceptTags: ['Fractions', 'Comparison', 'Addition', 'Visualization'],
    foxyTip: 'Which is bigger: 3/4 or 5/8? Use the compare mode to find out visually!',
    component: FractionVisualizer,
  },
  {
    id: 'builtin-trig-circle',
    title: 'Trigonometry Circle Lab',
    description: 'Explore sin, cos, and tan on the unit circle. See how angles create waves.',
    subject: 'math',
    grade: ['9', '10', '11', '12'],
    thumbnailEmoji: '🔄',
    difficulty: 3,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 10,
    conceptTags: ['Trigonometry', 'Unit Circle', 'Sin', 'Cos', 'Tan', 'Angles', 'Waves'],
    foxyTip: 'Drag the point around the circle and watch how sin and cos change. What happens at 90°?',
    component: TrigCircle,
  },
  {
    id: 'builtin-newton-laws',
    title: "Newton's Laws — Force & Motion",
    description: 'Push a block with different forces and masses. See F = ma in action with free body diagrams and real-time acceleration.',
    subject: 'physics',
    grade: ['9', '10', '11'],
    thumbnailEmoji: '🧱',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 10,
    conceptTags: ['Force', "Newton's Laws", 'Acceleration', 'Friction', 'F=ma'],
    foxyTip: 'Double the force with the same mass — what happens to acceleration? Now double the mass instead!',
    component: NewtonLaws,
  },
  {
    id: 'builtin-bohr-model',
    title: 'Bohr Atomic Model',
    description: 'Explore the electron configuration of the first 20 elements. Watch electrons orbit in shells and learn valence, valency, and element types.',
    subject: 'chemistry',
    grade: ['9', '10', '11'],
    thumbnailEmoji: '⚛️',
    difficulty: 2,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 8,
    conceptTags: ['Atom', 'Bohr Model', 'Electron Configuration', 'Shells', 'Valence'],
    foxyTip: 'Compare Na and Cl — why do they form NaCl? Look at their valence electrons!',
    component: BohrModel,
  },
  {
    id: 'builtin-quadratic-graph',
    title: 'Quadratic Equation Grapher',
    description: 'Graph y = ax² + bx + c and see roots, vertex, and discriminant change as you adjust coefficients.',
    subject: 'math',
    grade: ['9', '10', '11'],
    thumbnailEmoji: '📈',
    difficulty: 2,
    bloomLevel: 'analyze',
    estimatedTimeMinutes: 10,
    conceptTags: ['Quadratic', 'Parabola', 'Roots', 'Vertex', 'Discriminant'],
    foxyTip: 'Set a=1, b=0, c=1 — no real roots! The parabola doesn\'t touch the x-axis. What does the discriminant show?',
    component: QuadraticGraph,
  },
  {
    id: 'builtin-hookes-law',
    title: "Hooke's Law Spring Lab",
    description: 'Hang masses from a spring and watch it stretch. See F = kx on a live graph, then trigger oscillations!',
    subject: 'physics',
    grade: ['9', '10', '11'],
    thumbnailEmoji: '🔩',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 8,
    conceptTags: ["Hooke's Law", 'Spring', 'Elasticity', 'SHM', 'Energy'],
    foxyTip: 'Increase k (stiffer spring) and watch the oscillation period decrease. Why?',
    component: HookesLaw,
  },
  {
    id: 'builtin-linear-graph',
    title: 'Linear Equation Grapher',
    description: 'Graph y = mx + c and visualise slope, intercepts, and angle. Compare two lines to find intersections or check if they are parallel!',
    subject: 'math',
    grade: ['8', '9', '10'],
    thumbnailEmoji: '📊',
    difficulty: 1,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 8,
    conceptTags: ['Linear Equation', 'Slope', 'Intercept', 'Coordinate Geometry', 'Parallel Lines'],
    foxyTip: 'Two lines with the same slope never meet — they are parallel! What if their product of slopes is -1?',
    component: LinearGraph,
  },
  {
    id: 'builtin-chemical-balancer',
    title: 'Chemical Equation Balancer',
    description: 'Balance chemical equations by adjusting coefficients! Watch atoms count in real-time and discover the Law of Conservation of Mass.',
    subject: 'chemistry',
    grade: ['10'],
    thumbnailEmoji: '⚗️',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 8,
    conceptTags: ['Chemical Equations', 'Balancing', 'Conservation of Mass', 'Reactions', 'Stoichiometry'],
    foxyTip: 'Start by balancing the atom that appears in the fewest compounds. Save oxygen for last!',
    component: ChemicalBalancer,
  },
  {
    id: 'builtin-gas-laws',
    title: 'Gas Laws Lab (PV = nRT)',
    description: 'Explore Boyle\'s and Charles\'s Laws! Change pressure, volume, and temperature to see gas particles respond in real-time.',
    subject: 'chemistry',
    grade: ['11'],
    thumbnailEmoji: '🧪',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 10,
    conceptTags: ['Gas Laws', 'Boyle\'s Law', 'Charles\'s Law', 'PV=nRT', 'Ideal Gas', 'States of Matter'],
    foxyTip: 'In Boyle\'s mode, halve the volume and watch pressure double! That\'s PV = constant.',
    component: GasLaws,
  },
  {
    id: 'builtin-probability-lab',
    title: 'Probability Experiment Lab',
    description: 'Flip coins, roll dice, and discover the Law of Large Numbers! Watch experimental probability converge to theoretical as you increase trials.',
    subject: 'math',
    grade: ['10', '11'],
    thumbnailEmoji: '🎲',
    difficulty: 1,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 8,
    conceptTags: ['Probability', 'Random Experiment', 'Law of Large Numbers', 'Theoretical Probability', 'Experimental Probability'],
    foxyTip: 'Roll 1000 dice and watch each number approach 16.7% — that\'s the Law of Large Numbers!',
    component: ProbabilityLab,
  },
  {
    id: 'builtin-snells-law',
    title: 'Snell\'s Law — Refraction of Light',
    description: 'Bend light through different media! Change the angle and materials to discover Snell\'s Law and total internal reflection.',
    subject: 'physics',
    grade: ['10', '12'],
    thumbnailEmoji: '💎',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 8,
    conceptTags: ['Refraction', 'Snell\'s Law', 'Total Internal Reflection', 'Refractive Index', 'Critical Angle', 'Light'],
    foxyTip: 'Set medium 1 to glass and medium 2 to air, then increase the angle past the critical angle to see total internal reflection!',
    component: SnellsLaw,
  },
  {
    id: 'builtin-integration',
    title: 'Integration Visualizer',
    description: 'See how rectangles approximate the area under a curve! Increase rectangles to watch the Riemann sum converge to the exact integral.',
    subject: 'math',
    grade: ['12'],
    thumbnailEmoji: '∫',
    difficulty: 3,
    bloomLevel: 'analyze',
    estimatedTimeMinutes: 10,
    conceptTags: ['Integration', 'Definite Integral', 'Riemann Sum', 'Area Under Curve', 'Calculus'],
    foxyTip: 'Start with 5 rectangles, then slide to 100. Watch the error shrink — that\'s why we use integration!',
    component: IntegrationVisualizer,
  },
];
