'use client';

import dynamic from 'next/dynamic';

export interface BuiltInSimulation {
  id: string;
  title: string;
  description: string;
  subject: string;
  grade: string[];
  thumbnailEmoji: string;
  difficulty: number;
  bloomLevel: string;
  estimatedTimeMinutes: number;
  conceptTags: string[];
  foxyTip: string;
  component: React.ComponentType;
}

const OhmsLaw = dynamic(() => import('./OhmsLaw'), { ssr: false });
const PendulumLab = dynamic(() => import('./PendulumLab'), { ssr: false });
const LensRayDiagram = dynamic(() => import('./LensRayDiagram'), { ssr: false });
const WaveOnString = dynamic(() => import('./WaveOnString'), { ssr: false });
const ProjectileMotion = dynamic(() => import('./ProjectileMotion'), { ssr: false });
const PHScale = dynamic(() => import('./PHScale'), { ssr: false });
const PythagorasTheorem = dynamic(() => import('./PythagorasTheorem'), { ssr: false });
const FractionVisualizer = dynamic(() => import('./FractionVisualizer'), { ssr: false });
const TrigCircle = dynamic(() => import('./TrigCircle'), { ssr: false });
const NewtonLaws = dynamic(() => import('./NewtonLaws'), { ssr: false });
const BohrModel = dynamic(() => import('./BohrModel'), { ssr: false });
const QuadraticGraph = dynamic(() => import('./QuadraticGraph'), { ssr: false });
const HookesLaw = dynamic(() => import('./HookesLaw'), { ssr: false });
const LinearGraph = dynamic(() => import('./LinearGraph'), { ssr: false });
const ChemicalBalancer = dynamic(() => import('./ChemicalBalancer'), { ssr: false });
const GasLaws = dynamic(() => import('./GasLaws'), { ssr: false });
const ProbabilityLab = dynamic(() => import('./ProbabilityLab'), { ssr: false });
const SnellsLaw = dynamic(() => import('./SnellsLaw'), { ssr: false });
const IntegrationVisualizer = dynamic(() => import('./IntegrationVisualizer'), { ssr: false });
const SymmetryExplorer = dynamic(() => import('./SymmetryExplorer'), { ssr: false });
const AngleExplorer = dynamic(() => import('./AngleExplorer'), { ssr: false });
const BarGraphMaker = dynamic(() => import('./BarGraphMaker'), { ssr: false });
const PhotosynthesisLab = dynamic(() => import('./PhotosynthesisLab'), { ssr: false });
const HumanHeartLab = dynamic(() => import('./HumanHeartLab'), { ssr: false });
const ElectricCircuitBasic = dynamic(() => import('./ElectricCircuitBasic'), { ssr: false });
const MagnetFieldLines = dynamic(() => import('./MagnetFieldLines'), { ssr: false });
const LightReflection = dynamic(() => import('./LightReflection'), { ssr: false });
const CellStructure = dynamic(() => import('./CellStructure'), { ssr: false });
const AcidBaseIndicator = dynamic(() => import('./AcidBaseIndicator'), { ssr: false });
const RefractionLab = dynamic(() => import('./RefractionLab'), { ssr: false });
const RespirationLab = dynamic(() => import('./RespirationLab'), { ssr: false });
const MagneticFieldElectric = dynamic(() => import('./MagneticFieldElectric'), { ssr: false });
const MeterBridgeLab = dynamic(() => import('./MeterBridgeLab'), { ssr: false });
const ConvexLensLab = dynamic(() => import('./ConvexLensLab'), { ssr: false });
const PotentiometerLab = dynamic(() => import('./PotentiometerLab'), { ssr: false });
const MitosisLab = dynamic(() => import('./MitosisLab'), { ssr: false });
const PunnettSquareLab = dynamic(() => import('./PunnettSquareLab'), { ssr: false });
const DNAReplicationLab = dynamic(() => import('./DNAReplicationLab'), { ssr: false });
const AcidBaseTitration = dynamic(() => import('./AcidBaseTitration'), { ssr: false });
const ElectronConfiguration = dynamic(() => import('./ElectronConfiguration'), { ssr: false });
const StatesOfMatter = dynamic(() => import('./StatesOfMatter'), { ssr: false });
const ElectrochemicalCell = dynamic(() => import('./ElectrochemicalCell'), { ssr: false });
const VectorAddition = dynamic(() => import('./VectorAddition'), { ssr: false });
const SetTheoryVenn = dynamic(() => import('./SetTheoryVenn'), { ssr: false });
const StatisticsLab = dynamic(() => import('./StatisticsLab'), { ssr: false });
const CircuitBuilder = dynamic(() => import('./CircuitBuilder'), { ssr: false });
const MagneticField = dynamic(() => import('./MagneticField'), { ssr: false });
const WaveInterference = dynamic(() => import('./WaveInterference'), { ssr: false });
const CoulombsLaw = dynamic(() => import('./CoulombsLaw'), { ssr: false });
const SoundWaves = dynamic(() => import('./SoundWaves'), { ssr: false });

export const BUILT_IN_SIMULATIONS: BuiltInSimulation[] = [
  {
    id: 'builtin-ohms-law',
    title: "Ohm's Law Circuit Lab",
    description: 'Build a circuit and watch electrons flow! Change voltage and resistance to see how current changes in real-time.',
    subject: 'physics',
    grade: ['10', '11', '12'],
    thumbnailEmoji: '⚡',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 8,
    conceptTags: ['Electricity', "Ohm's Law", 'Current', 'Voltage', 'Resistance'],
    foxyTip: 'Try setting resistance very low — what happens to the current? This is why short circuits are dangerous!',
    component: OhmsLaw,
  },
  {
    id: 'builtin-pendulum',
    title: 'Pendulum Physics Lab',
    description: 'Swing a pendulum and discover what controls its period. Change gravity, length, and angle — which one matters most?',
    subject: 'physics',
    grade: ['9', '10', '11'],
    thumbnailEmoji: '🕐',
    difficulty: 2,
    bloomLevel: 'analyze',
    estimatedTimeMinutes: 10,
    conceptTags: ['Oscillation', 'Pendulum', 'Period', 'Gravity', 'SHM'],
    foxyTip: 'Does changing the angle change the period? Try it! The answer might surprise you for small angles.',
    component: PendulumLab,
  },
  {
    id: 'builtin-lens-ray',
    title: 'Lens & Mirror Ray Diagrams',
    description: 'Drag an object near a lens and watch the image form! See exactly how light bends through convex and concave lenses.',
    subject: 'physics',
    grade: ['10', '11', '12'],
    thumbnailEmoji: '🔍',
    difficulty: 3,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 12,
    conceptTags: ['Light', 'Refraction', 'Lens', 'Image Formation', 'Ray Diagram'],
    foxyTip: 'Move the object between F and 2F — this is the most asked case in board exams! Note if image is real or virtual.',
    component: LensRayDiagram,
  },
  {
    id: 'builtin-wave',
    title: 'Wave on a String',
    description: 'Create waves and see how frequency, amplitude, and speed are connected. Toggle standing waves to see nodes glow!',
    subject: 'physics',
    grade: ['9', '10', '11'],
    thumbnailEmoji: '🌊',
    difficulty: 2,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 8,
    conceptTags: ['Waves', 'Frequency', 'Amplitude', 'Wavelength', 'Standing Waves'],
    foxyTip: 'Watch the particles — they move up and down, not sideways! That\'s what makes it a transverse wave.',
    component: WaveOnString,
  },
  {
    id: 'builtin-projectile',
    title: 'Projectile Motion Launcher',
    description: 'Launch projectiles at different angles and speeds! Discover which angle gives maximum range and trace beautiful parabolas.',
    subject: 'physics',
    grade: ['11', '12'],
    thumbnailEmoji: '🚀',
    difficulty: 3,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 10,
    conceptTags: ['Projectile', 'Kinematics', 'Parabola', 'Range', 'Trajectory'],
    foxyTip: 'Try 45° for maximum range! Then try 30° and 60° — notice anything special about their ranges?',
    component: ProjectileMotion,
  },
  {
    id: 'builtin-ph-scale',
    title: 'pH Scale Explorer',
    description: 'Click everyday substances and watch the pH meter react! See litmus paper change color and learn acids from bases.',
    subject: 'chemistry',
    grade: ['7', '8', '9', '10'],
    thumbnailEmoji: '🧪',
    difficulty: 1,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 6,
    conceptTags: ['pH', 'Acids', 'Bases', 'Indicators', 'Litmus'],
    foxyTip: 'Your stomach acid has pH ~1.5! How does your body handle something so acidic?',
    component: PHScale,
  },
  {
    id: 'builtin-pythagoras',
    title: 'Pythagoras Theorem Explorer',
    description: 'Drag the triangle corners and watch the squares on each side change. See a² + b² = c² come alive!',
    subject: 'math',
    grade: ['8', '9', '10'],
    thumbnailEmoji: '📐',
    difficulty: 2,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 8,
    conceptTags: ['Pythagoras', 'Right Triangle', 'Geometry', 'Proof'],
    foxyTip: 'Try the 3-4-5 triangle — the simplest Pythagorean triple! Can you find others?',
    component: PythagorasTheorem,
  },
  {
    id: 'builtin-fractions',
    title: 'Pizza Fraction Lab',
    description: 'Slice pizzas into fractions! Compare halves, thirds, and quarters visually. Finally understand why 1/3 + 1/4 is not 2/7!',
    subject: 'math',
    grade: ['6', '7', '8'],
    thumbnailEmoji: '🍕',
    difficulty: 1,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 7,
    conceptTags: ['Fractions', 'Comparison', 'Addition', 'Visualization'],
    foxyTip: 'Which is bigger: 3/4 or 5/8? Use the compare mode to find out visually!',
    component: FractionVisualizer,
  },
  {
    id: 'builtin-trig-circle',
    title: 'Trigonometry Circle Lab',
    description: 'Explore sin, cos, and tan on the unit circle. See how angles create waves.',
    subject: 'math',
    grade: ['9', '10', '11', '12'],
    thumbnailEmoji: '🔄',
    difficulty: 3,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 10,
    conceptTags: ['Trigonometry', 'Unit Circle', 'Sin', 'Cos', 'Tan', 'Angles', 'Waves'],
    foxyTip: 'Drag the point around the circle and watch how sin and cos change. What happens at 90°?',
    component: TrigCircle,
  },
  {
    id: 'builtin-newton-laws',
    title: "Newton's Laws — Force & Motion",
    description: 'Push a block with different forces and masses. See F = ma in action with free body diagrams and real-time acceleration.',
    subject: 'physics',
    grade: ['9', '10', '11'],
    thumbnailEmoji: '🧱',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 10,
    conceptTags: ['Force', "Newton's Laws", 'Acceleration', 'Friction', 'F=ma'],
    foxyTip: 'Double the force with the same mass — what happens to acceleration? Now double the mass instead!',
    component: NewtonLaws,
  },
  {
    id: 'builtin-bohr-model',
    title: 'Bohr Atomic Model',
    description: 'Explore the electron configuration of the first 20 elements. Watch electrons orbit in shells and learn valence, valency, and element types.',
    subject: 'chemistry',
    grade: ['9', '10', '11'],
    thumbnailEmoji: '⚛️',
    difficulty: 2,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 8,
    conceptTags: ['Atom', 'Bohr Model', 'Electron Configuration', 'Shells', 'Valence'],
    foxyTip: 'Compare Na and Cl — why do they form NaCl? Look at their valence electrons!',
    component: BohrModel,
  },
  {
    id: 'builtin-quadratic-graph',
    title: 'Quadratic Equation Grapher',
    description: 'Graph y = ax² + bx + c and see roots, vertex, and discriminant change as you adjust coefficients.',
    subject: 'math',
    grade: ['9', '10', '11'],
    thumbnailEmoji: '📈',
    difficulty: 2,
    bloomLevel: 'analyze',
    estimatedTimeMinutes: 10,
    conceptTags: ['Quadratic', 'Parabola', 'Roots', 'Vertex', 'Discriminant'],
    foxyTip: 'Set a=1, b=0, c=1 — no real roots! The parabola doesn\'t touch the x-axis. What does the discriminant show?',
    component: QuadraticGraph,
  },
  {
    id: 'builtin-hookes-law',
    title: "Hooke's Law Spring Lab",
    description: 'Hang masses from a spring and watch it stretch. See F = kx on a live graph, then trigger oscillations!',
    subject: 'physics',
    grade: ['9', '10', '11'],
    thumbnailEmoji: '🔩',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 8,
    conceptTags: ["Hooke's Law", 'Spring', 'Elasticity', 'SHM', 'Energy'],
    foxyTip: 'Increase k (stiffer spring) and watch the oscillation period decrease. Why?',
    component: HookesLaw,
  },
  {
    id: 'builtin-linear-graph',
    title: 'Linear Equation Grapher',
    description: 'Graph y = mx + c and visualise slope, intercepts, and angle. Compare two lines to find intersections or check if they are parallel!',
    subject: 'math',
    grade: ['8', '9', '10'],
    thumbnailEmoji: '📊',
    difficulty: 1,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 8,
    conceptTags: ['Linear Equation', 'Slope', 'Intercept', 'Coordinate Geometry', 'Parallel Lines'],
    foxyTip: 'Two lines with the same slope never meet — they are parallel! What if their product of slopes is -1?',
    component: LinearGraph,
  },
  {
    id: 'builtin-chemical-balancer',
    title: 'Chemical Equation Balancer',
    description: 'Balance chemical equations by adjusting coefficients! Watch atoms count in real-time and discover the Law of Conservation of Mass.',
    subject: 'chemistry',
    grade: ['10'],
    thumbnailEmoji: '⚗️',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 8,
    conceptTags: ['Chemical Equations', 'Balancing', 'Conservation of Mass', 'Reactions', 'Stoichiometry'],
    foxyTip: 'Start by balancing the atom that appears in the fewest compounds. Save oxygen for last!',
    component: ChemicalBalancer,
  },
  {
    id: 'builtin-gas-laws',
    title: 'Gas Laws Lab (PV = nRT)',
    description: 'Explore Boyle\'s and Charles\'s Laws! Change pressure, volume, and temperature to see gas particles respond in real-time.',
    subject: 'chemistry',
    grade: ['11'],
    thumbnailEmoji: '🧪',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 10,
    conceptTags: ['Gas Laws', 'Boyle\'s Law', 'Charles\'s Law', 'PV=nRT', 'Ideal Gas', 'States of Matter'],
    foxyTip: 'In Boyle\'s mode, halve the volume and watch pressure double! That\'s PV = constant.',
    component: GasLaws,
  },
  {
    id: 'builtin-probability-lab',
    title: 'Probability Experiment Lab',
    description: 'Flip coins, roll dice, and discover the Law of Large Numbers! Watch experimental probability converge to theoretical as you increase trials.',
    subject: 'math',
    grade: ['10', '11'],
    thumbnailEmoji: '🎲',
    difficulty: 1,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 8,
    conceptTags: ['Probability', 'Random Experiment', 'Law of Large Numbers', 'Theoretical Probability', 'Experimental Probability'],
    foxyTip: 'Roll 1000 dice and watch each number approach 16.7% — that\'s the Law of Large Numbers!',
    component: ProbabilityLab,
  },
  {
    id: 'builtin-snells-law',
    title: 'Snell\'s Law — Refraction of Light',
    description: 'Bend light through different media! Change the angle and materials to discover Snell\'s Law and total internal reflection.',
    subject: 'physics',
    grade: ['10', '12'],
    thumbnailEmoji: '💎',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 8,
    conceptTags: ['Refraction', 'Snell\'s Law', 'Total Internal Reflection', 'Refractive Index', 'Critical Angle', 'Light'],
    foxyTip: 'Set medium 1 to glass and medium 2 to air, then increase the angle past the critical angle to see total internal reflection!',
    component: SnellsLaw,
  },
  {
    id: 'builtin-integration',
    title: 'Integration Visualizer',
    description: 'See how rectangles approximate the area under a curve! Increase rectangles to watch the Riemann sum converge to the exact integral.',
    subject: 'math',
    grade: ['12'],
    thumbnailEmoji: '∫',
    difficulty: 3,
    bloomLevel: 'analyze',
    estimatedTimeMinutes: 10,
    conceptTags: ['Integration', 'Definite Integral', 'Riemann Sum', 'Area Under Curve', 'Calculus'],
    foxyTip: 'Start with 5 rectangles, then slide to 100. Watch the error shrink — that\'s why we use integration!',
    component: IntegrationVisualizer,
  },
  {
    id: 'builtin-symmetry-explorer',
    title: 'Symmetry Explorer',
    description: 'Pick a shape and discover its lines of symmetry! Rotate it to see rotational symmetry in action — how many times does it map onto itself?',
    subject: 'math',
    grade: ['6', '7'],
    thumbnailEmoji: '🔷',
    difficulty: 1,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 7,
    conceptTags: ['Symmetry', 'Lines of Symmetry', 'Rotational Symmetry', 'Regular Polygons', 'Geometry'],
    foxyTip: 'A regular polygon with n sides always has exactly n lines of symmetry. Try the hexagon — it has 6!',
    component: SymmetryExplorer,
  },
  {
    id: 'builtin-angle-explorer',
    title: 'Angle Explorer',
    description: 'Drag a ray to make any angle! See it measured live with a protractor overlay, colour-coded by type — acute, right, obtuse, straight, or reflex.',
    subject: 'math',
    grade: ['6', '7'],
    thumbnailEmoji: '📐',
    difficulty: 1,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 7,
    conceptTags: ['Angles', 'Protractor', 'Acute', 'Right Angle', 'Obtuse', 'Reflex', 'Complementary', 'Supplementary'],
    foxyTip: 'Set the angle to 60° — its complementary angle is 30° and supplementary is 120°. They always add up to 90° and 180°!',
    component: AngleExplorer,
  },
  {
    id: 'builtin-bar-graph-maker',
    title: 'Bar Graph Maker',
    description: 'Enter your own data and watch a bar chart build in real time! Calculate mean, mode, and range, or switch to a fun pictograph view.',
    subject: 'math',
    grade: ['6', '7', '8'],
    thumbnailEmoji: '📊',
    difficulty: 1,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 8,
    conceptTags: ['Data Handling', 'Bar Graph', 'Pictograph', 'Mean', 'Mode', 'Range', 'Statistics'],
    foxyTip: 'Try the Cricket Scores preset — notice how two matches have the same score? That\'s the mode! Now change one value to something huge and watch the mean jump.',
    component: BarGraphMaker,
  },
  {
    id: 'builtin-photosynthesis',
    title: 'Photosynthesis Lab',
    description: 'Explore how light, CO\u2082, and water drive photosynthesis! Adjust each factor and watch glucose production and O\u2082 release change in real time.',
    subject: 'biology',
    grade: ['7', '8', '9', '10'],
    thumbnailEmoji: '\uD83C\uDF31',
    difficulty: 1,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 10,
    conceptTags: ['Photosynthesis', 'Chlorophyll', 'Glucose', 'Light Reaction', 'Stomata', 'Life Processes'],
    foxyTip: 'Set light to 100% but CO\u2082 to 10% — the rate is limited by CO\u2082! This is Liebig\'s Law of the Minimum.',
    component: PhotosynthesisLab,
  },
  {
    id: 'builtin-human-heart',
    title: 'Human Heart & Double Circulation',
    description: 'Watch blood flow through all four chambers of the heart! See the heartbeat cycle, valve action, and understand why we have double circulation.',
    subject: 'biology',
    grade: ['10', '11', '12'],
    thumbnailEmoji: '\u2764\uFE0F',
    difficulty: 2,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 12,
    conceptTags: ['Heart', 'Double Circulation', 'Pulmonary', 'Systemic', 'Valves', 'Life Processes'],
    foxyTip: 'Increase the heart rate to 120 BPM and watch the blood particles speed up. Why does your heart beat faster during exercise?',
    component: HumanHeartLab,
  },
  {
    id: 'builtin-electric-circuit-basic',
    title: 'Electric Circuit Builder',
    description: 'Build a simple circuit with a battery, bulbs, and switch! Toggle the switch ON/OFF and compare series vs parallel circuits.',
    subject: 'physics',
    grade: ['6', '7', '8'],
    thumbnailEmoji: '💡',
    difficulty: 1,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 8,
    conceptTags: ['Electricity', 'Circuit', 'Series', 'Parallel', 'Current', 'Switch'],
    foxyTip: 'In a series circuit, if one bulb breaks both go off. In parallel, the other stays on — that\'s how your home wiring works!',
    component: ElectricCircuitBasic,
  },
  {
    id: 'builtin-magnet-field-lines',
    title: 'Magnetic Field Lines',
    description: 'See field lines flow from North to South! Drag a compass around the magnet and watch the needle align. Try attract vs repel modes.',
    subject: 'physics',
    grade: ['6', '7', '8'],
    thumbnailEmoji: '🧲',
    difficulty: 1,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 8,
    conceptTags: ['Magnets', 'Magnetic Field', 'Field Lines', 'Compass', 'Poles', 'Attraction', 'Repulsion'],
    foxyTip: 'Drag the compass between two repelling magnets — can you find the neutral point where the field nearly cancels out?',
    component: MagnetFieldLines,
  },
  {
    id: 'builtin-light-reflection',
    title: 'Light Reflection Lab',
    description: 'Shine a ray on a mirror and discover the Law of Reflection! Drag the angle and see how angle i always equals angle r.',
    subject: 'physics',
    grade: ['6', '7', '8'],
    thumbnailEmoji: '🪞',
    difficulty: 1,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 7,
    conceptTags: ['Light', 'Reflection', 'Mirror', 'Angle of Incidence', 'Normal', 'Plane Mirror', 'Concave', 'Convex'],
    foxyTip: 'With a plane mirror, angle i ALWAYS equals angle r — no matter what angle you try. That\'s the Law of Reflection!',
    component: LightReflection,
  },
  {
    id: 'builtin-cell-structure',
    title: 'Cell Structure Explorer',
    description: 'Explore animal and plant cells! Click on each organelle to learn its function. Compare what plant cells have that animal cells don\'t.',
    subject: 'biology',
    grade: ['6', '7', '8'],
    thumbnailEmoji: '🔬',
    difficulty: 1,
    bloomLevel: 'remember',
    estimatedTimeMinutes: 10,
    conceptTags: ['Cell', 'Nucleus', 'Mitochondria', 'Chloroplast', 'Cell Wall', 'Organelles', 'Plant Cell', 'Animal Cell'],
    foxyTip: 'Plant cells have 3 things animal cells don\'t: a rigid cell wall, green chloroplasts, and one giant central vacuole. Can you spot them all?',
    component: CellStructure,
  },
  {
    id: 'builtin-acid-base-indicator',
    title: 'Acid-Base Indicator Lab',
    description: 'Test 6 solutions with 4 indicators and observe colour changes! Auto-fill a data table and discover how different indicators classify acids and bases.',
    subject: 'chemistry',
    grade: ['9', '10'],
    thumbnailEmoji: '\uD83E\uDDEA',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 10,
    conceptTags: ['Acids', 'Bases', 'Indicators', 'Litmus', 'Phenolphthalein', 'Methyl Orange', 'pH', 'Classification'],
    foxyTip: 'Phenolphthalein stays colourless in acid but turns pink in base — this makes it perfect for detecting bases! Why does it not work for acids?',
    component: AcidBaseIndicator,
  },
  {
    id: 'builtin-refraction-lab',
    title: 'Refraction Through Glass Slab & Prism',
    description: 'Watch light bend through a glass slab with lateral displacement, then switch to a prism and see white light split into VIBGYOR!',
    subject: 'physics',
    grade: ['9', '10'],
    thumbnailEmoji: '\uD83C\uDF08',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 10,
    conceptTags: ['Refraction', 'Glass Slab', 'Prism', 'Dispersion', 'VIBGYOR', 'Snell\'s Law', 'Lateral Displacement', 'Light'],
    foxyTip: 'In a glass slab, the emergent ray is always parallel to the incident ray — but shifted sideways. Try increasing the angle to see the lateral displacement grow!',
    component: RefractionLab,
  },
  {
    id: 'builtin-respiration-lab',
    title: 'Aerobic vs Anaerobic Respiration',
    description: 'Watch glucose break down in two pathways side-by-side! Compare ATP production, see molecules flow through mitochondria, and toggle yeast vs muscle cells.',
    subject: 'biology',
    grade: ['9', '10'],
    thumbnailEmoji: '\uD83E\uDEC1',
    difficulty: 2,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 8,
    conceptTags: ['Respiration', 'Aerobic', 'Anaerobic', 'ATP', 'Mitochondria', 'Glucose', 'Fermentation', 'Life Processes'],
    foxyTip: 'Aerobic respiration makes 38 ATP but anaerobic only makes 2 — that is 19x less! This is why you breathe harder during exercise — your muscles need oxygen for maximum energy.',
    component: RespirationLab,
  },
  {
    id: 'builtin-magnetic-field-electric',
    title: 'Magnetic Effects of Electric Current',
    description: 'See circular magnetic field lines form around a current-carrying wire! Toggle to solenoid mode, reverse current direction, and use the right-hand rule.',
    subject: 'physics',
    grade: ['9', '10'],
    thumbnailEmoji: '\uD83E\uDDF2',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 10,
    conceptTags: ['Magnetic Field', 'Electric Current', 'Right-Hand Rule', 'Solenoid', 'Compass', 'Electromagnetism'],
    foxyTip: 'Reverse the current direction and watch all the compass needles flip! The right-hand thumb rule tells you the field direction every time.',
    component: MagneticFieldElectric,
  },
  {
    id: 'builtin-meter-bridge',
    title: 'Meter Bridge — Find Unknown Resistance',
    description: 'Slide the jockey along a 1-metre wire to find the null point. Use the Wheatstone bridge principle R = S × l/(100−l) to determine unknown resistance.',
    subject: 'physics',
    grade: ['11', '12'],
    thumbnailEmoji: '🔌',
    difficulty: 3,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 12,
    conceptTags: ['Meter Bridge', 'Wheatstone Bridge', 'Resistance', 'Null Point', 'Galvanometer', 'Current Electricity'],
    foxyTip: 'Change the known resistance S and take multiple readings — the average gives a more accurate result. Watch the galvanometer needle carefully!',
    component: MeterBridgeLab,
  },
  {
    id: 'builtin-convex-lens',
    title: 'Convex Lens — Image Formation',
    description: 'Move the object to 5 standard positions and watch real/virtual images form. Verify the lens formula 1/v − 1/u = 1/f with live calculations.',
    subject: 'physics',
    grade: ['11', '12'],
    thumbnailEmoji: '🔭',
    difficulty: 3,
    bloomLevel: 'analyze',
    estimatedTimeMinutes: 15,
    conceptTags: ['Convex Lens', 'Image Formation', 'Lens Formula', 'Magnification', 'Real Image', 'Virtual Image', 'Ray Diagram'],
    foxyTip: 'Place the object exactly at 2F — the image is the same size! Now move it between F and 2F and notice the image is magnified. This is how projectors work.',
    component: ConvexLensLab,
  },
  {
    id: 'builtin-potentiometer',
    title: 'Potentiometer — Compare EMFs',
    description: 'Find balance lengths for two cells and compare their EMFs using E1/E2 = l1/l2. See animated current flow and understand why a potentiometer beats a voltmeter.',
    subject: 'physics',
    grade: ['11', '12'],
    thumbnailEmoji: '🔋',
    difficulty: 3,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 12,
    conceptTags: ['Potentiometer', 'EMF', 'Balance Length', 'Null Method', 'Galvanometer', 'Current Electricity'],
    foxyTip: 'At the balance point, no current flows through the galvanometer — that is why the potentiometer measures true EMF without any internal resistance drop!',
    component: PotentiometerLab,
  },
  {
    id: 'builtin-mitosis',
    title: 'Mitosis — Onion Root Tip',
    description: 'Watch a cell divide through all stages of mitosis! See chromosomes condense, align, and separate with animated transitions. Click any stage for detailed CBSE descriptions.',
    subject: 'biology',
    grade: ['11'],
    thumbnailEmoji: '\uD83E\uDDEC',
    difficulty: 2,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 10,
    conceptTags: ['Mitosis', 'Cell Division', 'Chromosomes', 'Prophase', 'Metaphase', 'Anaphase', 'Telophase', 'Cytokinesis'],
    foxyTip: 'Most cells in an onion root tip squash are in interphase — it is the longest phase! Can you spot the rare anaphase cells? They are the shortest phase.',
    component: MitosisLab,
  },
  {
    id: 'builtin-punnett-square',
    title: 'Punnett Square — Mendelian Genetics',
    description: 'Cross pea plants just like Mendel! Select parent genotypes and watch the Punnett square build with animated gametes. See the classic 3:1 and 9:3:3:1 ratios come alive.',
    subject: 'biology',
    grade: ['10', '12'],
    thumbnailEmoji: '\uD83C\uDF31',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 10,
    conceptTags: ['Genetics', 'Punnett Square', 'Monohybrid', 'Dihybrid', 'Mendel', 'Phenotype', 'Genotype', 'Heredity'],
    foxyTip: 'Try Tt x Tt for the classic 3:1 ratio. Then switch to dihybrid with TtRr x TtRr to see 9:3:3:1 — the most asked ratio in board exams!',
    component: PunnettSquareLab,
  },
  {
    id: 'builtin-dna-replication',
    title: 'DNA Replication Lab',
    description: 'Watch DNA replicate step by step! See helicase unwind the helix, DNA polymerase add bases, Okazaki fragments form, and DNA ligase seal the gaps. Colour-coded A-T and G-C base pairs.',
    subject: 'biology',
    grade: ['12'],
    thumbnailEmoji: '\uD83E\uDDEC',
    difficulty: 3,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 12,
    conceptTags: ['DNA Replication', 'Helicase', 'DNA Polymerase', 'Okazaki Fragments', 'Semi-conservative', 'Base Pairing', 'Molecular Biology'],
    foxyTip: 'The leading strand is synthesised continuously but the lagging strand needs Okazaki fragments — DNA polymerase can only work 5\' to 3\'! This is a key board exam concept.',
    component: DNAReplicationLab,
  },
  {
    id: 'builtin-acid-base-titration',
    title: 'Acid-Base Titration Lab',
    description: 'Drip NaOH into HCl and watch the pH curve build in real time! See the sharp equivalence point at pH 7 and observe the indicator colour change from red to purple.',
    subject: 'chemistry',
    grade: ['11', '12'],
    thumbnailEmoji: '\uD83E\uDDEA',
    difficulty: 3,
    bloomLevel: 'analyze',
    estimatedTimeMinutes: 12,
    conceptTags: ['Titration', 'pH', 'Acid-Base', 'Equivalence Point', 'Indicators', 'NaOH', 'HCl', 'Electrochemistry'],
    foxyTip: 'The pH jumps sharply from ~3 to ~11 near the equivalence point — this is why just one extra drop of base turns the indicator! This sharp jump is the key to accurate titration.',
    component: AcidBaseTitration,
  },
  {
    id: 'builtin-electron-configuration',
    title: 'Electron Configuration Explorer',
    description: 'Pick any element (H to Kr) and see its electrons fill into orbital boxes following Aufbau principle and Hund\'s rule. Spot the special cases Cr and Cu!',
    subject: 'chemistry',
    grade: ['11', '12'],
    thumbnailEmoji: '\u26DB',
    difficulty: 2,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 10,
    conceptTags: ['Electron Configuration', 'Aufbau Principle', "Hund's Rule", 'Orbital', 'Pauli Exclusion', 'Atomic Structure', 'Periodic Table'],
    foxyTip: 'Chromium (Cr, Z=24) and Copper (Cu, Z=29) are exceptions to Aufbau — they steal an electron from 4s to half-fill or fully fill 3d. Extra stability from half-filled and fully-filled d orbitals!',
    component: ElectronConfiguration,
  },
  {
    id: 'builtin-states-of-matter',
    title: 'States of Matter — Particle Simulation',
    description: 'Watch 60 particles transition from solid to liquid to gas as temperature rises! See lattice vibration, free flow, and rapid gas motion emerge from the same particles.',
    subject: 'chemistry',
    grade: ['9', '10'],
    thumbnailEmoji: '\uD83D\uDD25',
    difficulty: 1,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 8,
    conceptTags: ['States of Matter', 'Solid', 'Liquid', 'Gas', 'Kinetic Theory', 'Melting', 'Boiling', 'Particle Motion'],
    foxyTip: 'Notice that particles in a solid vibrate in place but never change position — that\'s why solids have a fixed shape! Increase temperature past 300K to see them break free into liquid.',
    component: StatesOfMatter,
  },
  {
    id: 'builtin-electrochemical-cell',
    title: 'Electrochemical Cell (Galvanic)',
    description: 'Watch the Daniell cell in action! See electrons flow from anode to cathode, ions migrate through the salt bridge, and calculate E°cell using electrode potentials.',
    subject: 'chemistry',
    grade: ['11', '12'],
    thumbnailEmoji: '\uD83D\uDD0B',
    difficulty: 3,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 12,
    conceptTags: ['Electrochemistry', 'Galvanic Cell', 'Daniell Cell', 'EMF', 'Electrode Potential', 'Oxidation', 'Reduction', 'Nernst Equation', 'Salt Bridge'],
    foxyTip: 'The anode always loses mass (metal dissolves) while the cathode gains mass (metal deposits) — try the Zn|Cu cell and trace where each atom goes! This is electrolysis in reverse.',
    component: ElectrochemicalCell,
  },
  {
    id: 'builtin-vector-addition',
    title: 'Vector Addition — Parallelogram Law',
    description: 'Set magnitude and angle for two vectors and watch the resultant form using the parallelogram law! See Cartesian components, resultant magnitude, and direction angle live.',
    subject: 'math',
    grade: ['11', '12'],
    thumbnailEmoji: '➡️',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 10,
    conceptTags: ['Vectors', 'Parallelogram Law', 'Resultant', 'Components', 'Magnitude', 'Direction', 'Triangle Law'],
    foxyTip: 'Try angle A = 0° and angle B = 90° — the resultant is the hypotenuse! Change both to 45° and compare — the magnitude is highest when they point the same way.',
    component: VectorAddition,
  },
  {
    id: 'builtin-set-theory-venn',
    title: 'Set Theory & Venn Diagrams',
    description: 'Enter elements for Set A, Set B, and Universal Set U. Click regions on the Venn diagram to explore union, intersection, difference, and complement with the inclusion-exclusion formula.',
    subject: 'math',
    grade: ['11', '12'],
    thumbnailEmoji: '⭕',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 8,
    conceptTags: ['Sets', 'Venn Diagram', 'Union', 'Intersection', 'Complement', 'Difference', 'Inclusion-Exclusion', 'Universal Set'],
    foxyTip: 'n(A∪B) = n(A) + n(B) − n(A∩B) — try changing the sets so A∩B is empty. The union is just their sum! This is the most important formula in sets for board exams.',
    component: SetTheoryVenn,
  },
  {
    id: 'builtin-statistics-lab',
    title: 'Statistics Lab — Measures of Central Tendency',
    description: 'Input any dataset or pick a preset and instantly compute mean, median, mode, variance, and standard deviation! See a histogram with mean and median lines marked.',
    subject: 'math',
    grade: ['9', '10', '11', '12'],
    thumbnailEmoji: '📊',
    difficulty: 2,
    bloomLevel: 'analyze',
    estimatedTimeMinutes: 10,
    conceptTags: ['Statistics', 'Mean', 'Median', 'Mode', 'Variance', 'Standard Deviation', 'Histogram', 'Data Handling', 'Range'],
    foxyTip: 'Add one very large outlier to the exam scores — watch the mean jump but the median barely moves! Mean is sensitive to outliers, median is not. That is why median household income is used, not mean.',
    component: StatisticsLab,
  },
  {
    id: 'builtin-circuit-builder',
    title: 'Circuit Builder — Series & Parallel',
    description: 'Build series and parallel circuits with adjustable resistors and voltage. Apply Kirchhoff\'s laws and Ohm\'s law — watch wire colour shift with current intensity.',
    subject: 'physics',
    grade: ['9', '10', '11', '12'],
    thumbnailEmoji: '🔌',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 10,
    conceptTags: ['Circuits', 'Series', 'Parallel', "Ohm's Law", "Kirchhoff's Law", 'Current', 'Voltage', 'Resistance', 'Power'],
    foxyTip: 'In a parallel circuit, adding more resistors drops total resistance and increases current! Try both at 10Ω — parallel gives half the resistance of series. That is why home appliances are wired in parallel.',
    component: CircuitBuilder,
  },
  {
    id: 'builtin-magnetic-field',
    title: 'Magnetic Field Around a Conductor',
    description: 'Visualize concentric magnetic field lines around a current-carrying wire. Apply the right-hand rule, reverse current direction, and calculate B at distances using Ampere\'s law.',
    subject: 'physics',
    grade: ['10', '11', '12'],
    thumbnailEmoji: '🧲',
    difficulty: 2,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 8,
    conceptTags: ['Magnetic Field', "Ampere's Law", 'Right-Hand Rule', 'Current', 'Electromagnetism', 'Field Lines'],
    foxyTip: 'Reverse the current and watch all field arrows flip direction! The field is strongest near the wire — notice how circles are more crowded there. This is the inverse relationship B ∝ 1/r.',
    component: MagneticField,
  },
  {
    id: 'builtin-wave-interference',
    title: 'Wave Interference & Superposition',
    description: 'Superpose two sine waves and observe constructive and destructive interference. Adjust frequency, amplitude, and phase to create beat patterns and standing waves.',
    subject: 'physics',
    grade: ['11', '12'],
    thumbnailEmoji: '〰️',
    difficulty: 3,
    bloomLevel: 'analyze',
    estimatedTimeMinutes: 12,
    conceptTags: ['Wave Interference', 'Superposition', 'Constructive', 'Destructive', 'Beats', 'Phase', 'Amplitude', 'Frequency'],
    foxyTip: 'Set both waves to the same frequency but phase = 180° — they cancel out completely! That is destructive interference. Now set phase = 0° for maximum constructive interference. Noise-cancelling headphones use this!',
    component: WaveInterference,
  },
  {
    id: 'builtin-coulombs-law',
    title: "Coulomb's Law — Electrostatic Forces",
    description: 'Place two point charges and watch the electrostatic force update instantly. Adjust charge magnitudes, distance, and signs to verify F = kq₁q₂/r² in real-time.',
    subject: 'physics',
    grade: ['10', '11', '12'],
    thumbnailEmoji: '⚛️',
    difficulty: 2,
    bloomLevel: 'apply',
    estimatedTimeMinutes: 10,
    conceptTags: ["Coulomb's Law", 'Electrostatics', 'Electric Force', 'Point Charges', 'Inverse Square Law', 'Attraction', 'Repulsion'],
    foxyTip: 'Double the distance and the force drops to 1/4 — that is the inverse square law! Now double both charges and the force quadruples. This is why Coulomb\'s law is so powerful for board exam numericals.',
    component: CoulombsLaw,
  },
  {
    id: 'builtin-sound-waves',
    title: 'Sound Waves — Frequency & Amplitude',
    description: 'See sound as both a longitudinal (particle compression) wave and a transverse sine wave simultaneously. Adjust frequency and amplitude to visualize wavelength, period, and wave speed.',
    subject: 'physics',
    grade: ['9', '10', '11'],
    thumbnailEmoji: '🔊',
    difficulty: 1,
    bloomLevel: 'understand',
    estimatedTimeMinutes: 8,
    conceptTags: ['Sound Waves', 'Longitudinal Wave', 'Compression', 'Rarefaction', 'Frequency', 'Amplitude', 'Wavelength', 'Wave Speed'],
    foxyTip: 'Increase frequency and watch the wavelength shrink — v = fλ means if speed is fixed, higher frequency = shorter wavelength. That is why a piccolo (high frequency) sounds sharper than a bass guitar!',
    component: SoundWaves,
  },
];
