/**
 * Server-safe simulation metadata.
 *
 * The canonical `BUILT_IN_SIMULATIONS` array in `index.tsx` is a `'use client'`
 * module because each entry carries a React component (via next/dynamic). Server
 * routes (Daily Lab Mission, etc.) need only the metadata — id, title, subject,
 * grade pool, emoji, time-estimate. This file mirrors that data without React
 * imports so it can be consumed by the App Router server runtime.
 *
 * Keep this file in sync with `BUILT_IN_SIMULATIONS` in `./index.tsx` whenever a
 * simulation is added/removed/regraded. There is a parity test in
 * `src/__tests__/api/daily-lab.test.ts` that asserts equal length and id-set.
 */

export interface BuiltInSimulationMeta {
  id: string;
  title: string;
  subject: string;
  grade: string[];
  thumbnailEmoji: string;
  estimatedTimeMinutes: number;
}

export const BUILT_IN_SIMULATIONS_META: BuiltInSimulationMeta[] = [
  { id: 'builtin-ohms-law', title: "Ohm's Law Circuit Lab", subject: 'physics', grade: ['10','11','12'], thumbnailEmoji: '⚡', estimatedTimeMinutes: 8 },
  { id: 'builtin-pendulum', title: 'Pendulum Physics Lab', subject: 'physics', grade: ['9','10','11'], thumbnailEmoji: '🕐', estimatedTimeMinutes: 10 },
  { id: 'builtin-lens-ray', title: 'Lens & Mirror Ray Diagrams', subject: 'physics', grade: ['10','11','12'], thumbnailEmoji: '🔍', estimatedTimeMinutes: 12 },
  { id: 'builtin-wave', title: 'Wave on a String', subject: 'physics', grade: ['9','10','11'], thumbnailEmoji: '🌊', estimatedTimeMinutes: 8 },
  { id: 'builtin-projectile', title: 'Projectile Motion Launcher', subject: 'physics', grade: ['11','12'], thumbnailEmoji: '🚀', estimatedTimeMinutes: 10 },
  { id: 'builtin-ph-scale', title: 'pH Scale Explorer', subject: 'chemistry', grade: ['7','8','9','10'], thumbnailEmoji: '🧪', estimatedTimeMinutes: 6 },
  { id: 'builtin-pythagoras', title: 'Pythagoras Theorem Explorer', subject: 'math', grade: ['8','9','10'], thumbnailEmoji: '📐', estimatedTimeMinutes: 8 },
  { id: 'builtin-fractions', title: 'Pizza Fraction Lab', subject: 'math', grade: ['6','7','8'], thumbnailEmoji: '🍕', estimatedTimeMinutes: 7 },
  { id: 'builtin-trig-circle', title: 'Trigonometry Circle Lab', subject: 'math', grade: ['9','10','11','12'], thumbnailEmoji: '🔄', estimatedTimeMinutes: 10 },
  { id: 'builtin-newton-laws', title: "Newton's Laws — Force & Motion", subject: 'physics', grade: ['9','10','11'], thumbnailEmoji: '🧱', estimatedTimeMinutes: 10 },
  { id: 'builtin-bohr-model', title: 'Bohr Atomic Model', subject: 'chemistry', grade: ['9','10','11'], thumbnailEmoji: '⚛️', estimatedTimeMinutes: 8 },
  { id: 'builtin-quadratic-graph', title: 'Quadratic Equation Grapher', subject: 'math', grade: ['9','10','11'], thumbnailEmoji: '📈', estimatedTimeMinutes: 10 },
  { id: 'builtin-hookes-law', title: "Hooke's Law Spring Lab", subject: 'physics', grade: ['9','10','11'], thumbnailEmoji: '🔩', estimatedTimeMinutes: 8 },
  { id: 'builtin-linear-graph', title: 'Linear Equation Grapher', subject: 'math', grade: ['8','9','10'], thumbnailEmoji: '📊', estimatedTimeMinutes: 8 },
  { id: 'builtin-chemical-balancer', title: 'Chemical Equation Balancer', subject: 'chemistry', grade: ['10'], thumbnailEmoji: '⚗️', estimatedTimeMinutes: 8 },
  { id: 'builtin-gas-laws', title: 'Gas Laws Lab (PV = nRT)', subject: 'chemistry', grade: ['11'], thumbnailEmoji: '🧪', estimatedTimeMinutes: 10 },
  { id: 'builtin-probability-lab', title: 'Probability Experiment Lab', subject: 'math', grade: ['10','11'], thumbnailEmoji: '🎲', estimatedTimeMinutes: 8 },
  { id: 'builtin-snells-law', title: "Snell's Law — Refraction of Light", subject: 'physics', grade: ['10','12'], thumbnailEmoji: '💎', estimatedTimeMinutes: 8 },
  { id: 'builtin-integration', title: 'Integration Visualizer', subject: 'math', grade: ['12'], thumbnailEmoji: '∫', estimatedTimeMinutes: 10 },
  { id: 'builtin-symmetry-explorer', title: 'Symmetry Explorer', subject: 'math', grade: ['6','7'], thumbnailEmoji: '🔷', estimatedTimeMinutes: 7 },
  { id: 'builtin-angle-explorer', title: 'Angle Explorer', subject: 'math', grade: ['6','7'], thumbnailEmoji: '📐', estimatedTimeMinutes: 7 },
  { id: 'builtin-bar-graph-maker', title: 'Bar Graph Maker', subject: 'math', grade: ['6','7','8'], thumbnailEmoji: '📊', estimatedTimeMinutes: 8 },
  { id: 'builtin-photosynthesis', title: 'Photosynthesis Lab', subject: 'biology', grade: ['7','8','9','10'], thumbnailEmoji: '🌱', estimatedTimeMinutes: 10 },
  { id: 'builtin-human-heart', title: 'Human Heart & Double Circulation', subject: 'biology', grade: ['10','11','12'], thumbnailEmoji: '❤️', estimatedTimeMinutes: 12 },
  { id: 'builtin-electric-circuit-basic', title: 'Electric Circuit Builder', subject: 'physics', grade: ['6','7','8'], thumbnailEmoji: '💡', estimatedTimeMinutes: 8 },
  { id: 'builtin-magnet-field-lines', title: 'Magnetic Field Lines', subject: 'physics', grade: ['6','7','8'], thumbnailEmoji: '🧲', estimatedTimeMinutes: 8 },
  { id: 'builtin-light-reflection', title: 'Light Reflection Lab', subject: 'physics', grade: ['6','7','8'], thumbnailEmoji: '🪞', estimatedTimeMinutes: 7 },
  { id: 'builtin-cell-structure', title: 'Cell Structure Explorer', subject: 'biology', grade: ['6','7','8'], thumbnailEmoji: '🔬', estimatedTimeMinutes: 10 },
  { id: 'builtin-acid-base-indicator', title: 'Acid-Base Indicator Lab', subject: 'chemistry', grade: ['9','10'], thumbnailEmoji: '🧪', estimatedTimeMinutes: 10 },
  { id: 'builtin-refraction-lab', title: 'Refraction Through Glass Slab & Prism', subject: 'physics', grade: ['9','10'], thumbnailEmoji: '🌈', estimatedTimeMinutes: 10 },
  { id: 'builtin-respiration-lab', title: 'Aerobic vs Anaerobic Respiration', subject: 'biology', grade: ['9','10'], thumbnailEmoji: '🫁', estimatedTimeMinutes: 8 },
  { id: 'builtin-magnetic-field-electric', title: 'Magnetic Effects of Electric Current', subject: 'physics', grade: ['9','10'], thumbnailEmoji: '🧲', estimatedTimeMinutes: 10 },
  { id: 'builtin-meter-bridge', title: 'Meter Bridge — Find Unknown Resistance', subject: 'physics', grade: ['11','12'], thumbnailEmoji: '🔌', estimatedTimeMinutes: 12 },
  { id: 'builtin-convex-lens', title: 'Convex Lens — Image Formation', subject: 'physics', grade: ['11','12'], thumbnailEmoji: '🔭', estimatedTimeMinutes: 15 },
  { id: 'builtin-potentiometer', title: 'Potentiometer — Compare EMFs', subject: 'physics', grade: ['11','12'], thumbnailEmoji: '🔋', estimatedTimeMinutes: 12 },
  { id: 'builtin-mitosis', title: 'Mitosis — Onion Root Tip', subject: 'biology', grade: ['11'], thumbnailEmoji: '🧬', estimatedTimeMinutes: 10 },
  { id: 'builtin-punnett-square', title: 'Punnett Square — Mendelian Genetics', subject: 'biology', grade: ['10','12'], thumbnailEmoji: '🌱', estimatedTimeMinutes: 10 },
  { id: 'builtin-dna-replication', title: 'DNA Replication Lab', subject: 'biology', grade: ['12'], thumbnailEmoji: '🧬', estimatedTimeMinutes: 12 },
  { id: 'builtin-acid-base-titration', title: 'Acid-Base Titration Lab', subject: 'chemistry', grade: ['11','12'], thumbnailEmoji: '🧪', estimatedTimeMinutes: 12 },
  { id: 'builtin-electron-configuration', title: 'Electron Configuration Explorer', subject: 'chemistry', grade: ['11','12'], thumbnailEmoji: '⛛', estimatedTimeMinutes: 10 },
  { id: 'builtin-states-of-matter', title: 'States of Matter — Particle Simulation', subject: 'chemistry', grade: ['9','10'], thumbnailEmoji: '🔥', estimatedTimeMinutes: 8 },
  { id: 'builtin-electrochemical-cell', title: 'Electrochemical Cell (Galvanic)', subject: 'chemistry', grade: ['11','12'], thumbnailEmoji: '🔋', estimatedTimeMinutes: 12 },
  { id: 'builtin-vector-addition', title: 'Vector Addition — Parallelogram Law', subject: 'math', grade: ['11','12'], thumbnailEmoji: '➡️', estimatedTimeMinutes: 10 },
  { id: 'builtin-set-theory-venn', title: 'Set Theory & Venn Diagrams', subject: 'math', grade: ['11','12'], thumbnailEmoji: '⭕', estimatedTimeMinutes: 8 },
  { id: 'builtin-statistics-lab', title: 'Statistics Lab — Measures of Central Tendency', subject: 'math', grade: ['9','10','11','12'], thumbnailEmoji: '📊', estimatedTimeMinutes: 10 },
  { id: 'builtin-circuit-builder', title: 'Circuit Builder — Series & Parallel', subject: 'physics', grade: ['9','10','11','12'], thumbnailEmoji: '🔌', estimatedTimeMinutes: 10 },
  { id: 'builtin-magnetic-field', title: 'Magnetic Field Around a Conductor', subject: 'physics', grade: ['10','11','12'], thumbnailEmoji: '🧲', estimatedTimeMinutes: 8 },
  { id: 'builtin-wave-interference', title: 'Wave Interference & Superposition', subject: 'physics', grade: ['11','12'], thumbnailEmoji: '〰️', estimatedTimeMinutes: 12 },
  { id: 'builtin-coulombs-law', title: "Coulomb's Law — Electrostatic Forces", subject: 'physics', grade: ['10','11','12'], thumbnailEmoji: '⚛️', estimatedTimeMinutes: 10 },
  { id: 'builtin-sound-waves', title: 'Sound Waves — Frequency & Amplitude', subject: 'physics', grade: ['9','10','11'], thumbnailEmoji: '🔊', estimatedTimeMinutes: 8 },
  { id: 'builtin-simple-machines', title: 'Simple Machines Lab', subject: 'physics', grade: ['6','7','8'], thumbnailEmoji: '⚙️', estimatedTimeMinutes: 8 },
  { id: 'builtin-mirror-reflection', title: 'Law of Reflection', subject: 'physics', grade: ['6','7','8'], thumbnailEmoji: '🪞', estimatedTimeMinutes: 7 },
  { id: 'builtin-electric-charge', title: "Electric Charges & Coulomb's Force", subject: 'physics', grade: ['8','9'], thumbnailEmoji: '⚡', estimatedTimeMinutes: 7 },
  { id: 'builtin-heat-transfer', title: 'Heat Transfer: Conduction, Convection & Radiation', subject: 'physics', grade: ['7','8'], thumbnailEmoji: '🔥', estimatedTimeMinutes: 8 },
  { id: 'builtin-speed-distance-time', title: 'Speed, Distance & Time Graph', subject: 'physics', grade: ['6','7'], thumbnailEmoji: '🚗', estimatedTimeMinutes: 7 },
  { id: 'builtin-light-refraction', title: "Light Refraction — Snell's Law", subject: 'physics', grade: ['8','9','10'], thumbnailEmoji: '💡', estimatedTimeMinutes: 8 },
  { id: 'builtin-solar-system', title: 'Solar System Orbital Simulator', subject: 'physics', grade: ['6','7','8'], thumbnailEmoji: '🪐', estimatedTimeMinutes: 10 },
  { id: 'builtin-weather-cycle', title: 'The Water Cycle', subject: 'physics', grade: ['6','7'], thumbnailEmoji: '🌧️', estimatedTimeMinutes: 7 },
  { id: 'builtin-echo-sound', title: 'Echo & Speed of Sound Calculator', subject: 'physics', grade: ['8','9'], thumbnailEmoji: '📢', estimatedTimeMinutes: 7 },
  { id: 'builtin-shadow-formation', title: 'Shadow Formation & Umbra/Penumbra', subject: 'physics', grade: ['6','7'], thumbnailEmoji: '🌑', estimatedTimeMinutes: 7 },
  { id: 'builtin-electric-motor', title: 'DC Electric Motor', subject: 'physics', grade: ['10','11'], thumbnailEmoji: '🔄', estimatedTimeMinutes: 10 },
  { id: 'builtin-transformer', title: 'Transformer — Turns Ratio & Voltage', subject: 'physics', grade: ['10','11','12'], thumbnailEmoji: '🔌', estimatedTimeMinutes: 8 },
  { id: 'builtin-resistors-series', title: 'Resistors in Series — Voltage Divider', subject: 'physics', grade: ['10','11'], thumbnailEmoji: '⚡', estimatedTimeMinutes: 8 },
  { id: 'builtin-concave-mirror', title: 'Concave Mirror Ray Diagrams', subject: 'physics', grade: ['10','11','12'], thumbnailEmoji: '🔍', estimatedTimeMinutes: 12 },
  { id: 'builtin-convex-lens-new', title: 'Convex Lens — Ray Construction', subject: 'physics', grade: ['10','11','12'], thumbnailEmoji: '🔭', estimatedTimeMinutes: 12 },
  { id: 'builtin-free-body-diagram', title: 'Free Body Diagram Builder', subject: 'physics', grade: ['9','10','11'], thumbnailEmoji: '⬆️', estimatedTimeMinutes: 9 },
  { id: 'builtin-archimedes', title: "Archimedes' Principle — Buoyancy Lab", subject: 'physics', grade: ['9','10'], thumbnailEmoji: '🚢', estimatedTimeMinutes: 9 },
  { id: 'builtin-em-spectrum', title: 'Electromagnetic Spectrum Explorer', subject: 'physics', grade: ['10','11','12'], thumbnailEmoji: '🌈', estimatedTimeMinutes: 8 },
  { id: 'builtin-capacitor-charging', title: 'Capacitor Charging in RC Circuit', subject: 'physics', grade: ['12'], thumbnailEmoji: '🔋', estimatedTimeMinutes: 12 },
  { id: 'builtin-doppler-effect', title: 'Doppler Effect Simulator', subject: 'physics', grade: ['11','12'], thumbnailEmoji: '🚨', estimatedTimeMinutes: 10 },
  { id: 'builtin-young-double-slit', title: "Young's Double Slit — Interference", subject: 'physics', grade: ['12'], thumbnailEmoji: '〰️', estimatedTimeMinutes: 12 },
  { id: 'builtin-nuclear-decay', title: 'Radioactive Decay & Half-Life', subject: 'physics', grade: ['12'], thumbnailEmoji: '☢️', estimatedTimeMinutes: 10 },
  { id: 'builtin-photoelectric-effect', title: 'Photoelectric Effect Lab', subject: 'physics', grade: ['12'], thumbnailEmoji: '💥', estimatedTimeMinutes: 10 },
  { id: 'builtin-element-classifier', title: 'Element Classifier — Metals, Non-metals, Metalloids', subject: 'chemistry', grade: ['8','9'], thumbnailEmoji: '🧪', estimatedTimeMinutes: 7 },
  { id: 'builtin-mixtures-separation', title: 'Separating Mixtures Lab', subject: 'chemistry', grade: ['6','7','8'], thumbnailEmoji: '⚗️', estimatedTimeMinutes: 8 },
  { id: 'builtin-water-electrolysis', title: 'Electrolysis of Water', subject: 'chemistry', grade: ['8','9'], thumbnailEmoji: '💧', estimatedTimeMinutes: 7 },
  { id: 'builtin-litmus-test', title: 'Litmus Test Lab', subject: 'chemistry', grade: ['6','7','8'], thumbnailEmoji: '🧫', estimatedTimeMinutes: 7 },
  { id: 'builtin-atom-builder', title: 'Atom Builder — Protons, Neutrons, Electrons', subject: 'chemistry', grade: ['8','9','10'], thumbnailEmoji: '⚛️', estimatedTimeMinutes: 9 },
  { id: 'builtin-periodic-trends', title: 'Periodic Table Trends', subject: 'chemistry', grade: ['10','11','12'], thumbnailEmoji: '📊', estimatedTimeMinutes: 10 },
  { id: 'builtin-crystallization', title: 'Crystallization — From Solution to Crystals', subject: 'chemistry', grade: ['7','8'], thumbnailEmoji: '💎', estimatedTimeMinutes: 7 },
  { id: 'builtin-rusting-experiment', title: 'Rusting — Conditions for Corrosion', subject: 'chemistry', grade: ['8','9'], thumbnailEmoji: '🔩', estimatedTimeMinutes: 8 },
  { id: 'builtin-molarity-calculator', title: 'Molarity — Concentration Calculator', subject: 'chemistry', grade: ['10','11'], thumbnailEmoji: '🧪', estimatedTimeMinutes: 8 },
  { id: 'builtin-exo-endo-thermic', title: 'Exothermic & Endothermic Reactions', subject: 'chemistry', grade: ['10','11'], thumbnailEmoji: '🌡️', estimatedTimeMinutes: 9 },
  { id: 'builtin-ionic-covalent-bonds', title: 'Ionic vs Covalent Bond Formation', subject: 'chemistry', grade: ['9','10','11'], thumbnailEmoji: '🔗', estimatedTimeMinutes: 9 },
  { id: 'builtin-metal-reactivity', title: 'Metal Reactivity Series — Displacement Reactions', subject: 'chemistry', grade: ['10','11'], thumbnailEmoji: '⚗️', estimatedTimeMinutes: 9 },
  { id: 'builtin-carbon-allotropes', title: 'Carbon Allotropes — Diamond, Graphite & Fullerene', subject: 'chemistry', grade: ['11','12'], thumbnailEmoji: '💎', estimatedTimeMinutes: 9 },
  { id: 'builtin-chemical-kinetics', title: 'Chemical Kinetics — Rate vs Concentration', subject: 'chemistry', grade: ['12'], thumbnailEmoji: '📈', estimatedTimeMinutes: 12 },
  { id: 'builtin-buffer-solution', title: 'Buffer Solution — pH Stability', subject: 'chemistry', grade: ['12'], thumbnailEmoji: '⚗️', estimatedTimeMinutes: 10 },
  { id: 'builtin-galvanic-cell', title: 'Galvanic Cell — Daniell Cell Lab', subject: 'chemistry', grade: ['12'], thumbnailEmoji: '🔋', estimatedTimeMinutes: 12 },
  { id: 'builtin-molecular-geometry', title: 'VSEPR Molecular Geometry', subject: 'chemistry', grade: ['11','12'], thumbnailEmoji: '🔬', estimatedTimeMinutes: 9 },
  { id: 'builtin-food-web', title: 'Food Web Builder', subject: 'biology', grade: ['6','7','8'], thumbnailEmoji: '🌿', estimatedTimeMinutes: 9 },
  { id: 'builtin-digestive-system', title: 'Human Digestive System — Follow the Food', subject: 'biology', grade: ['7','8','10'], thumbnailEmoji: '🫁', estimatedTimeMinutes: 10 },
  { id: 'builtin-plant-parts', title: 'Plant Parts & Functions', subject: 'biology', grade: ['6','7'], thumbnailEmoji: '🌱', estimatedTimeMinutes: 8 },
  { id: 'builtin-alveoli-breathing', title: 'Breathing & Gas Exchange in Alveoli', subject: 'biology', grade: ['7','8','10'], thumbnailEmoji: '🫁', estimatedTimeMinutes: 8 },
  { id: 'builtin-seed-germination', title: 'Seed Germination Conditions', subject: 'biology', grade: ['6','7'], thumbnailEmoji: '🌱', estimatedTimeMinutes: 8 },
  { id: 'builtin-animal-classification', title: 'Animal Classification — Vertebrates & Invertebrates', subject: 'biology', grade: ['6','7','8'], thumbnailEmoji: '🦎', estimatedTimeMinutes: 8 },
  { id: 'builtin-water-purification', title: 'Water Treatment Plant — Step by Step', subject: 'biology', grade: ['7','8'], thumbnailEmoji: '💧', estimatedTimeMinutes: 8 },
  { id: 'builtin-heart-circulation', title: 'Heart & Double Circulation', subject: 'biology', grade: ['10','11'], thumbnailEmoji: '❤️', estimatedTimeMinutes: 10 },
  { id: 'builtin-nervous-system', title: 'Neuron Structure & Reflex Arc', subject: 'biology', grade: ['10','11','12'], thumbnailEmoji: '🧠', estimatedTimeMinutes: 10 },
  { id: 'builtin-meiosis-stages', title: 'Meiosis — All 8 Stages Animated', subject: 'biology', grade: ['11','12'], thumbnailEmoji: '🔬', estimatedTimeMinutes: 12 },
  { id: 'builtin-ecosystem-balance', title: 'Predator-Prey Population Dynamics', subject: 'biology', grade: ['10','11','12'], thumbnailEmoji: '🐰', estimatedTimeMinutes: 10 },
  { id: 'builtin-evolution-tree', title: 'Phylogenetic Tree — Common Ancestors', subject: 'biology', grade: ['10','11','12'], thumbnailEmoji: '🌳', estimatedTimeMinutes: 10 },
  { id: 'builtin-protein-synthesis', title: 'Protein Synthesis — Transcription & Translation', subject: 'biology', grade: ['12'], thumbnailEmoji: '🧬', estimatedTimeMinutes: 12 },
  { id: 'builtin-hormone-regulation', title: 'Hormone Regulation & Feedback Loops', subject: 'biology', grade: ['11','12'], thumbnailEmoji: '⚗️', estimatedTimeMinutes: 10 },
  { id: 'builtin-gene-expression', title: 'Gene Expression — Lac Operon', subject: 'biology', grade: ['12'], thumbnailEmoji: '🧬', estimatedTimeMinutes: 12 },
  { id: 'builtin-fraction-operations', title: 'Fraction Operations — Visual Pie Charts', subject: 'math', grade: ['6','7','8'], thumbnailEmoji: '🍕', estimatedTimeMinutes: 8 },
  { id: 'builtin-area-perimeter', title: 'Area & Perimeter Shape Builder', subject: 'math', grade: ['6','7','8'], thumbnailEmoji: '📐', estimatedTimeMinutes: 8 },
  { id: 'builtin-number-line', title: 'Integer Operations on a Number Line', subject: 'math', grade: ['6','7'], thumbnailEmoji: '🔢', estimatedTimeMinutes: 7 },
  { id: 'builtin-symmetry-lines-lab', title: 'Symmetry in Alphabets & Polygons', subject: 'math', grade: ['6','7'], thumbnailEmoji: '🔡', estimatedTimeMinutes: 7 },
  { id: 'builtin-data-handling', title: 'Data Handling — Charts & Statistics', subject: 'math', grade: ['6','7','8'], thumbnailEmoji: '📊', estimatedTimeMinutes: 8 },
  { id: 'builtin-coordinate-geometry', title: 'Coordinate Geometry Lab', subject: 'math', grade: ['9','10'], thumbnailEmoji: '📍', estimatedTimeMinutes: 10 },
  { id: 'builtin-surface-area-volume', title: 'Surface Area & Volume of 3D Shapes', subject: 'math', grade: ['9','10'], thumbnailEmoji: '📦', estimatedTimeMinutes: 10 },
  { id: 'builtin-circle-theorems', title: 'Circle Theorems — Interactive Proofs', subject: 'math', grade: ['9','10'], thumbnailEmoji: '⭕', estimatedTimeMinutes: 11 },
  { id: 'builtin-limits-visualizer', title: 'Limits — Graphical Approach', subject: 'math', grade: ['11','12'], thumbnailEmoji: '📉', estimatedTimeMinutes: 11 },
  { id: 'builtin-matrix-operations', title: 'Matrix Operations — Add, Multiply, Determinant', subject: 'math', grade: ['11','12'], thumbnailEmoji: '🔢', estimatedTimeMinutes: 12 },
];
