/**
 * agents/runtime/layers/l7-deploy.ts — L7 deploy automation.
 *
 * Fires when the L6 critic approves a cycle whose L4 produced a
 * non-empty diff. Two steps:
 *
 *   1. Push the worktree's branch to origin (so the human can find it
 *      after the cron's ephemeral runner is gone).
 *   2. Open a pull request via `gh pr create`, with a body that
 *      includes the full audit trail (cycle id, L4 summary, evaluator
 *      verdicts, critic reasoning, rubric version).
 *
 * What this does NOT do (deliberate Phase γ safety stance):
 *   - No auto-merge. Humans decide whether to merge. PRs are visible
 *     in the team's normal review surface.
 *   - No force-push, no rewrite. Each cycle's branch is created from
 *     main and pushed fresh.
 *   - No tag, release, or production-side action.
 *
 * Gating:
 *   - --real-l7 CLI flag (off by default; requires --commit AND a real
 *     cycle that didn't reject).
 *   - Verdict must be `approve` (request_changes / reject / escalate
 *     don't push).
 *   - files_changed must be non-empty (no empty-PR spam).
 *   - GITHUB_TOKEN (in CI) or the user's gh CLI auth (locally) must be
 *     available.
 *
 * Each PR body ends with [mesh-cron] so reviewers can filter the noise.
 */

import { spawnSync } from 'node:child_process';
import type { WorktreeHandle } from '../worktree';

const PR_BASE_BRANCH = 'main';
const PR_LABEL = 'mesh-cron'; // future: applied via gh pr edit --add-label

export interface L7DeployInputs {
  worktree: WorktreeHandle;
  cycleId: string;
  taskId: string;
  goalText: string;
  l4Summary: string;
  l4FilesChanged: Array<{ path: string; change: string }>;
  l5Verdicts: Array<{ evaluator: string; verdict: string; blocking: boolean }>;
  l6Decision: 'approve' | 'request_changes' | 'reject' | 'escalate_to_human';
  l6Reasoning: string;
  rubricVersion: string;
  tokensSpent: number;
}

export interface L7DeployResult {
  skipped: boolean;
  skipReason?: string;
  pushed: boolean;
  prUrl: string | null;
  notes: string;
}

/**
 * Decide whether L7 should fire. Exposed so tests can pin the gate
 * conditions without spawning git/gh.
 */
export function shouldDeploy(args: {
  decision: L7DeployInputs['l6Decision'];
  filesChanged: number;
}): { go: boolean; reason: string } {
  if (args.decision !== 'approve') {
    return { go: false, reason: `verdict=${args.decision} (only approve triggers push)` };
  }
  if (args.filesChanged === 0) {
    return { go: false, reason: 'empty diff (no files changed; nothing to PR)' };
  }
  return { go: true, reason: 'approve + non-empty diff' };
}

/**
 * Compose the PR body. Exposed so the test can pin its shape.
 */
export function buildPrBody(args: L7DeployInputs): string {
  const evidence = args.l5Verdicts
    .map(v => `- \`${v.evaluator}\`: **${v.verdict}**${v.blocking ? ' (blocking)' : ''}`)
    .join('\n');
  const filesList = args.l4FilesChanged
    .map(f => `- ${f.change}: \`${f.path}\``)
    .join('\n');
  // Cap the critic reasoning to keep PR bodies sane.
  const reasoning =
    args.l6Reasoning.length > 4000
      ? args.l6Reasoning.slice(0, 4000) + '\n\n_…(critic reasoning truncated; full text in cycle_evaluations row)_'
      : args.l6Reasoning;

  return [
    `## Autonomous cycle — ${args.l6Decision.toUpperCase()}`,
    '',
    `**Cycle goal:**`,
    '> ' + args.goalText.replace(/\n/g, '\n> '),
    '',
    `**Cycle id:** \`${args.cycleId}\``,
    `**Task id:** \`${args.taskId}\``,
    `**Tokens spent (L4):** ${args.tokensSpent}`,
    `**Rubric version:** \`${args.rubricVersion}\``,
    '',
    '### L4 summary (agent\'s own words)',
    args.l4Summary,
    '',
    '### Files changed',
    filesList || '_(none)_',
    '',
    '### L5 evaluator verdicts',
    evidence,
    '',
    '### L6 critic reasoning',
    reasoning,
    '',
    '---',
    '',
    `_Generated by the autonomous mesh runtime ([agents/runtime/AUTOMATION.md](agents/runtime/AUTOMATION.md))._`,
    `_Human reviewer decides whether to merge — no auto-merge._`,
    '',
    '[mesh-cron]',
  ].join('\n');
}

// ─── git/gh shell-outs ────────────────────────────────────────────────

function run(cmd: string, args: string[], cwd: string): { ok: boolean; out: string; err: string } {
  const r = spawnSync(cmd, args, {
    cwd,
    encoding: 'utf8',
    env: process.env,
    shell: false, // native binaries; avoid cmd.exe word-splitting on paths with spaces
  });
  return {
    ok: r.status === 0,
    out: (r.stdout ?? '').trim(),
    err: (r.stderr ?? r.stdout ?? '').trim(),
  };
}

// ─── The L7 worker ────────────────────────────────────────────────────

export async function runDeploy(args: L7DeployInputs): Promise<L7DeployResult> {
  const gate = shouldDeploy({
    decision: args.l6Decision,
    filesChanged: args.l4FilesChanged.length,
  });
  if (!gate.go) {
    return {
      skipped: true,
      skipReason: gate.reason,
      pushed: false,
      prUrl: null,
      notes: `L7 skipped: ${gate.reason}`,
    };
  }

  const wt = args.worktree;

  // Push the branch from the worktree's view (it knows the branch).
  // We push from the repo root (not the worktree dir) since `git push`
  // from a worktree pushes the worktree's HEAD — both work, repo-root
  // is more conventional.
  const push = run('git', ['push', '--set-upstream', 'origin', wt.branch], wt.repoRoot);
  if (!push.ok) {
    return {
      skipped: false,
      pushed: false,
      prUrl: null,
      notes: `L7 push failed: ${push.err.slice(0, 800)}`,
    };
  }

  // Open the PR via gh CLI. We use --base main; the head is the auto/* branch.
  // PR title comes from the goal (cap length); body has the full audit trail.
  const title = `[mesh-cron] ${args.goalText.slice(0, 80)}`;
  const body = buildPrBody(args);

  // gh pr create supports --body-file '-' to read body from stdin; we use
  // an inline --body for simplicity since the runtime's body is bounded.
  const ghArgs = [
    'pr', 'create',
    '--base', PR_BASE_BRANCH,
    '--head', wt.branch,
    '--title', title,
    '--body', body,
  ];
  // Apply the mesh-cron label only if it exists in the repo (gh fails if
  // the label is unknown). Detection is optional; if --add-label exists
  // post-create, the human can apply it.
  const prRes = run('gh', ghArgs, wt.repoRoot);
  if (!prRes.ok) {
    return {
      skipped: false,
      pushed: true,
      prUrl: null,
      notes:
        `L7 push succeeded but gh pr create failed: ${prRes.err.slice(0, 800)}.\n` +
        `Branch is on origin: ${wt.branch} — a human can open the PR manually.`,
    };
  }
  // gh pr create prints the PR URL on the last stdout line.
  const prUrl = prRes.out.split(/\r?\n/).filter(Boolean).pop() ?? null;

  // Best-effort: try to add the mesh-cron label (silent on failure).
  if (prUrl) {
    run('gh', ['pr', 'edit', prUrl, '--add-label', PR_LABEL], wt.repoRoot);
  }

  return {
    skipped: false,
    pushed: true,
    prUrl,
    notes: `L7 pushed ${wt.branch} and opened PR: ${prUrl ?? '(no URL captured)'}`,
  };
}

// Help the importer; not needed at runtime.
export const __INTERNAL = { run, PR_BASE_BRANCH, PR_LABEL };
