/**
 * Alfanumrik — Pedagogy v2 / Wave 3
 * Synthesis summary prompt assembly.
 *
 * The bilingual one-page parent-share text is generated by Claude Haiku
 * from a structured SynthesisBundle. This module owns prompt assembly
 * (testable, no LLM calls) plus a small reply parser that extracts the
 * EN: / HI: sections from the model's output.
 *
 * The actual Claude call lives in the Edge Function `monthly-synthesis-builder`
 * (Wave 3 Task 4) — keep prompt logic here, IO there.
 *
 * Safety rails (encoded in the prompt):
 *   - P11 — no fabrication. The model is told to use the exact mastery
 *     numbers given; it must not invent counts or topics not in the
 *     bundle.
 *   - P13 — no PII beyond student name + grade. Email/phone/school are
 *     not in the prompt because the bundle does not carry them.
 *   - ~300-word soft cap so the WhatsApp delivery is parent-readable.
 *
 * Spec: docs/superpowers/specs/2026-05-08-pedagogy-v2-three-speed-rhythm-design.md §5.3
 */

import type { SynthesisBundle } from '../../learn/monthly-synthesis-orchestrator';

export interface SynthesisSummaryParams {
  studentName: string;
  studentGrade: string;          // P5: string '6'..'12'
  bundle: SynthesisBundle;
  language: 'en' | 'hi' | 'both';
}

export interface SynthesisSummaryReply {
  textEn: string;
  textHi: string;
}

/**
 * Build the system+user prompt content for a synthesis summary.
 * Returned string is intended to be passed to Claude as the system prompt;
 * the user message is a fixed "Generate the bilingual summary." sent by
 * the Edge Function caller.
 */
export function buildSynthesisSummaryPrompt(params: SynthesisSummaryParams): string {
  const { studentName, studentGrade, bundle, language } = params;
  const md = bundle.masteryDelta;
  const artifactCount = bundle.weeklyArtifactIds.length;

  const chaptersList = md.chaptersTouched.length > 0
    ? md.chaptersTouched.map((c) => `  - ${c}`).join('\n')
    : '  (no chapters touched this month — light month)';

  const mockLine = bundle.chapterMockSummary
    ? `Chapter mock: ${bundle.chapterMockSummary.totalQuestions} questions across ${bundle.chapterMockSummary.chapters.join(', ')}, target difficulty ${bundle.chapterMockSummary.targetDifficulty} (${Math.round(bundle.chapterMockSummary.targetDifficulty * 100)}%).`
    : 'Chapter mock: not generated (no chapters touched this month).';

  const artifactLine = artifactCount > 0
    ? `${artifactCount} weekly artifacts produced this month (Curiosity Dive pieces).`
    : `0 artifacts this month — the student did not produce a weekly Curiosity Dive piece.`;

  const langInstruction = (() => {
    if (language === 'both') {
      return [
        'OUTPUT FORMAT — IMPORTANT:',
        'Produce TWO sections, each tagged with a marker on its own line:',
        '  EN:',
        '  <English text, ~150 words>',
        '  HI:',
        '  <Hindi text, ~150 words; same content, parent-readable register>',
        'No content outside the EN: and HI: blocks.',
      ].join('\n');
    }
    if (language === 'en') {
      return 'OUTPUT FORMAT: English only, single paragraph or short paragraphs.';
    }
    return 'OUTPUT FORMAT: Hindi only, parent-readable register.';
  })();

  return [
    'You are writing a one-page monthly progress summary for a parent.',
    'Audience: a parent who is not a subject-matter expert. Plain language. No jargon.',
    'Aim for ~300 words total. Hard cap at 300 words.',
    '',
    'CRITICAL — DO NOT FABRICATE:',
    '- Use ONLY the numbers and topic names provided below. Do not invent counts, scores, or chapter names.',
    '- If a number is 0 or a list is empty, say so honestly. Do not pad with optimistic claims.',
    '',
    `Student: ${studentName} (Grade ${studentGrade})`,
    `Month: ${bundle.monthLabel}`,
    '',
    'This month\'s mastery delta:',
    `- ${md.topicsMastered} topics newly mastered`,
    `- ${md.topicsImproved} topics improved`,
    `- ${md.topicsRegressed} topics regressed`,
    '- Chapters touched:',
    chaptersList,
    '',
    artifactLine,
    mockLine,
    '',
    'Tone: warm, honest, specific. Lead with the most concrete win or the most actionable area to support. Avoid generic phrases like "great progress" — name a specific topic or chapter.',
    '',
    langInstruction,
  ].join('\n');
}

// ─── Reply parser ──────────────────────────────────────────────────────────

const EN_MARKER = /^\s*EN:\s*$/m;
const HI_MARKER = /^\s*HI:\s*$/m;

/**
 * Parse a Claude reply that may contain `EN:` and `HI:` markers into a
 * structured { textEn, textHi } object. Robust to:
 *   - English-only replies (no markers): full reply goes into textEn,
 *     textHi is empty string.
 *   - Surrounding whitespace and blank lines between marker and content.
 *   - Markers on their own line (the prompt instructs this format).
 *
 * Does NOT validate length — the Edge Function caller is responsible for
 * the ~300-word soft cap.
 */
export function parseSynthesisSummaryReply(reply: string): SynthesisSummaryReply {
  const enIdx = reply.search(EN_MARKER);
  const hiIdx = reply.search(HI_MARKER);

  if (enIdx === -1 && hiIdx === -1) {
    // No markers — treat the whole reply as English.
    return { textEn: reply.trim(), textHi: '' };
  }

  let textEn = '';
  let textHi = '';

  if (enIdx !== -1) {
    const afterEn = reply.slice(enIdx).replace(EN_MARKER, '');
    const enEnd = hiIdx !== -1 && hiIdx > enIdx
      ? afterEn.search(HI_MARKER)
      : -1;
    textEn = (enEnd === -1 ? afterEn : afterEn.slice(0, enEnd)).trim();
  }

  if (hiIdx !== -1) {
    const afterHi = reply.slice(hiIdx).replace(HI_MARKER, '');
    textHi = afterHi.trim();
  }

  return { textEn, textHi };
}
