/**
 * scripts/gen-openapi.build.mts — the tsx-executed half of `npm run gen:openapi`.
 *
 * Imports the Zod OpenAPIRegistry (the single source of truth), generates an
 * OpenAPI 3.1 document, and prints it as pretty-printed JSON with STABLE
 * (recursively sorted) key order to STDOUT. All diagnostics go to STDERR so
 * the parent `gen-openapi.mjs` can capture clean JSON from stdout.
 *
 * Stable key ordering matters: zod-to-openapi does not guarantee object key
 * order, and an unstable artifact would make the CI drift-check (git diff)
 * flap. Sorting keys recursively makes the committed `openapi/v2.json`
 * deterministic across machines and library patch versions.
 */

import { OpenApiGeneratorV31 } from '@asteasolutions/zod-to-openapi';
import { registry } from '../packages/lib/src/api/v2/contract';

/** Recursively sort object keys so JSON.stringify is deterministic. Arrays keep order. */
function sortKeysDeep(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(sortKeysDeep);
  }
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const key of Object.keys(value as Record<string, unknown>).sort()) {
      out[key] = sortKeysDeep((value as Record<string, unknown>)[key]);
    }
    return out;
  }
  return value;
}

function main(): void {
  const generator = new OpenApiGeneratorV31(registry.definitions);

  const doc = generator.generateDocument({
    openapi: '3.1.0',
    info: {
      title: 'Alfanumrik /v2 API',
      version: '2.0.0',
      description:
        'The Alfanumrik /v2 contract. Single source of truth: packages/lib/src/api/v2/contract.ts (Zod). ' +
        'This document is generated by `npm run gen:openapi` and consumed by the Dart client ' +
        'codegen (`npm run gen:dart`). Do not edit by hand.',
    },
    servers: [{ url: '/api', description: 'Alfanumrik API base path' }],
  });

  const stable = sortKeysDeep(doc);
  // Pretty-print, 2-space indent. The parent script appends the trailing newline.
  process.stdout.write(JSON.stringify(stable, null, 2));
}

main();
