-- 20260903180000_p2_5_phase2b_merge_rls_policies_batch1.sql
--
-- P2-5 phase 2, batch 1 of Category B (2026-09-03 launch audit, CEO-
-- approved "full consolidation, small batches with tests" — the follow-up
-- to phase 2a's 20260903170000, which handled only the byte-identical
-- duplicate policies).
--
-- Category B is the multiple_permissive_policies advisor findings where
-- the policies for a (table, command, role) group are GENUINELY DIFFERENT
-- — each implements a distinct access rule (own row, teacher-of, guardian-
-- of, school-admin-of, etc.) — as opposed to phase 2a's byte-identical
-- naming-drift duplicates. Postgres evaluates every applicable PERMISSIVE
-- policy for a role+command and ORs the results together; it cannot
-- short-circuit on the first match. Combining N separate policies into ONE
-- policy whose USING clause is the OR of all N original clauses is
-- semantics-preserving (identical access before and after — a row is
-- visible under the merged policy iff it was visible under at least one of
-- the originals) while removing the per-row evaluation overhead of
-- checking N separate policy objects.
--
-- METHOD (verification discipline, matching phase 1's RLS-initplan fix):
-- every USING clause below was generated by a script from the EXACT
-- current qual text pulled live from pg_policies immediately before
-- writing this file — never hand-retyped — specifically to rule out
-- transcription drift in this much nested SQL. The script only ORs
-- clauses together; it never attempts to algebraically simplify a merged
-- expression (e.g. dropping a clause that looks logically subsumed by
-- another), because that kind of "cleanup" requires confidently proving
-- equivalence of arbitrary RLS predicates — a mistake there could silently
-- narrow OR widen access on production student data. The one exception is
-- documented below (chapters) precisely because it's NOT this migration's
-- doing — it's a pre-existing fact this migration surfaces, not creates.
--
-- SCOPE (this batch): 15 tables where exactly 2 PERMISSIVE policies exist
-- for the same (command, role) pair. Chosen as batch 1 because they're the
-- simplest shape (a straight 2-way OR) to validate the method against
-- before tackling the larger 3-6-policy groups (quiz_responses,
-- foxy_chat_messages, students, etc. — tracked as later batches). All 15
-- are SELECT-only merges: none of the source policies carry a WITH CHECK
-- (SELECT policies never do), so only USING needed merging.
--
-- ── NOTABLE FINDING, not a change made by this migration ──────────────────
-- public.chapters's two pre-existing policies were `(is_active = true)` and
-- `true` — since these are OR'd, the unconditional `true` policy ALONE
-- already made the table's SELECT access unconditional; the `is_active`
-- check has been a dead no-op for every authenticated caller since
-- whichever migration added the second ("phase1") policy. The merge below
-- preserves this EXACT pre-existing behavior (`(is_active = true) OR
-- true`, which is `true`) rather than unilaterally tightening it to
-- `is_active = true` only — deciding whether inactive/archived chapters
-- SHOULD be hidden from students is a product-scope call, not a hygiene
-- fix, and is out of scope here. Flagged for the CEO/assessment owner.
--
-- Naming: the merged-policy name follows `<table>_select_merged`, an
-- existing convention already present in this schema (see
-- `students_select_merged` on public.students) rather than a new one
-- invented for this migration.

-- ── public.assessment_schedule (SELECT, authenticated): merge 2 policies ──
DROP POLICY IF EXISTS "assessment_schedule_own_select" ON public.assessment_schedule;
DROP POLICY IF EXISTS "assessment_schedule_teacher_select" ON public.assessment_schedule;
CREATE POLICY "assessment_schedule_select_merged" ON public.assessment_schedule
  FOR SELECT TO authenticated
  USING (
  (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  OR ((student_id IN ( SELECT cs.student_id
   FROM ((class_students cs
     JOIN class_teachers ct ON ((ct.class_id = cs.class_id)))
     JOIN teachers t ON ((t.id = ct.teacher_id)))
  WHERE (t.auth_user_id = ( SELECT auth.uid() AS uid)))))
  );

-- ── public.audit_logs (SELECT, authenticated): merge 2 policies ──
DROP POLICY IF EXISTS "audit_logs_select" ON public.audit_logs;
DROP POLICY IF EXISTS "school_admins_see_school_audit_logs" ON public.audit_logs;
CREATE POLICY "audit_logs_select_merged" ON public.audit_logs
  FOR SELECT TO authenticated
  USING (
  (((auth_user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT auth.uid() AS uid) IN ( SELECT admin_users.auth_user_id
   FROM admin_users
  WHERE (admin_users.is_active = true)))))
  OR (((school_id IS NOT NULL) AND (school_id IN ( SELECT sa.school_id
   FROM school_admins sa
  WHERE ((sa.auth_user_id = ( SELECT auth.uid() AS uid)) AND (sa.is_active = true))))))
  );

-- ── public.chapter_progress (SELECT, authenticated): merge 2 policies ──
DROP POLICY IF EXISTS "chapter_progress_admin_select" ON public.chapter_progress;
DROP POLICY IF EXISTS "chapter_progress_own_select" ON public.chapter_progress;
CREATE POLICY "chapter_progress_select_merged" ON public.chapter_progress
  FOR SELECT TO authenticated
  USING (
  (is_admin())
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );

-- ── public.chapter_study_sessions (SELECT, authenticated): merge 2 policies ──
DROP POLICY IF EXISTS "chapter_study_sessions_own_select" ON public.chapter_study_sessions;
DROP POLICY IF EXISTS "chapter_study_sessions_owner_read" ON public.chapter_study_sessions;
CREATE POLICY "chapter_study_sessions_select_merged" ON public.chapter_study_sessions
  FOR SELECT TO authenticated
  USING (
  (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  OR (((student_id IN ( SELECT get_my_student_ids() AS get_my_student_ids)) OR is_guardian_of(student_id) OR is_teacher_of(student_id)))
  );

-- ── public.chapters (SELECT, authenticated): merge 2 policies ──
-- See "NOTABLE FINDING" in the header — this merge preserves the
-- pre-existing (already-unconditional) behavior verbatim.
DROP POLICY IF EXISTS "chapters_authenticated_select" ON public.chapters;
DROP POLICY IF EXISTS "chapters_phase1_authenticated_select" ON public.chapters;
CREATE POLICY "chapters_select_merged" ON public.chapters
  FOR SELECT TO authenticated
  USING (
  ((is_active = true))
  OR (true)
  );

-- ── public.class_enrollments (SELECT, authenticated): merge 2 policies ──
DROP POLICY IF EXISTS "class_enrollments_own_select" ON public.class_enrollments;
DROP POLICY IF EXISTS "class_enrollments_teacher_select" ON public.class_enrollments;
CREATE POLICY "class_enrollments_select_merged" ON public.class_enrollments
  FOR SELECT TO authenticated
  USING (
  (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  OR ((class_id IN ( SELECT ct.class_id
   FROM (class_teachers ct
     JOIN teachers t ON ((t.id = ct.teacher_id)))
  WHERE (t.auth_user_id = ( SELECT auth.uid() AS uid)))))
  );

-- ── public.classroom_lesson_plans (SELECT, authenticated): merge 2 policies ──
DROP POLICY IF EXISTS "Students can view classroom lesson plans" ON public.classroom_lesson_plans;
DROP POLICY IF EXISTS "Teachers can view classroom lesson plans" ON public.classroom_lesson_plans;
CREATE POLICY "classroom_lesson_plans_select_merged" ON public.classroom_lesson_plans
  FOR SELECT TO authenticated
  USING (
  ((class_id IN ( SELECT cs.class_id
   FROM (class_students cs
     JOIN students s ON ((s.id = cs.student_id)))
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid)))))
  OR ((class_id IN ( SELECT ct.class_id
   FROM (class_teachers ct
     JOIN teachers t ON ((t.id = ct.teacher_id)))
  WHERE (t.auth_user_id = ( SELECT auth.uid() AS uid)))))
  );

-- ── public.institution_entitlements (SELECT, authenticated): merge 2 policies ──
DROP POLICY IF EXISTS "school_admin read own" ON public.institution_entitlements;
DROP POLICY IF EXISTS "super_admin read all" ON public.institution_entitlements;
CREATE POLICY "institution_entitlements_select_merged" ON public.institution_entitlements
  FOR SELECT TO authenticated
  USING (
  ((school_id IN ( SELECT sa.school_id
   FROM school_admins sa
  WHERE ((sa.auth_user_id = ( SELECT auth.uid() AS uid)) AND (sa.is_active = true)))))
  OR ((EXISTS ( SELECT 1
   FROM (user_roles ur
     JOIN roles r ON ((r.id = ur.role_id)))
  WHERE ((ur.auth_user_id = ( SELECT auth.uid() AS uid)) AND (r.name = ANY (ARRAY['admin'::text, 'super_admin'::text])) AND (ur.is_active = true) AND ((ur.expires_at IS NULL) OR (ur.expires_at > now()))))))
  );

-- ── public.leaderboard (SELECT, authenticated): merge 2 policies ──
DROP POLICY IF EXISTS "leaderboard_own_select" ON public.leaderboard;
DROP POLICY IF EXISTS "leaderboard_owner_read" ON public.leaderboard;
CREATE POLICY "leaderboard_select_merged" ON public.leaderboard
  FOR SELECT TO authenticated
  USING (
  (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  OR (((student_id IN ( SELECT get_my_student_ids() AS get_my_student_ids)) OR is_guardian_of(student_id) OR is_teacher_of(student_id)))
  );

-- ── public.retrieval_traces (SELECT, public): merge 2 policies ──
DROP POLICY IF EXISTS "rt_super_admin_select" ON public.retrieval_traces;
DROP POLICY IF EXISTS "rt_user_select" ON public.retrieval_traces;
CREATE POLICY "retrieval_traces_select_merged" ON public.retrieval_traces
  FOR SELECT TO public
  USING (
  ((EXISTS ( SELECT 1
   FROM (user_roles ur
     JOIN roles r ON ((r.id = ur.role_id)))
  WHERE ((ur.auth_user_id = ( SELECT auth.uid() AS uid)) AND (ur.is_active = true) AND ((ur.expires_at IS NULL) OR (ur.expires_at > now())) AND (r.name = ANY (ARRAY['super_admin'::text, 'admin'::text]))))))
  OR ((user_id = ( SELECT auth.uid() AS uid)))
  );

-- ── public.school_announcements (SELECT, authenticated): merge 2 policies ──
DROP POLICY IF EXISTS "announcements_school_admin_select" ON public.school_announcements;
DROP POLICY IF EXISTS "announcements_student_select" ON public.school_announcements;
CREATE POLICY "school_announcements_select_merged" ON public.school_announcements
  FOR SELECT TO authenticated
  USING (
  (((school_id = get_admin_school_id()) OR is_school_admin_of(school_id)))
  OR (((is_active = true) AND (published_at IS NOT NULL) AND (published_at <= now()) AND (school_id IN ( SELECT students.school_id
   FROM students
  WHERE ((students.auth_user_id = ( SELECT auth.uid() AS uid)) AND (students.school_id IS NOT NULL))))))
  );

-- ── public.school_exams (SELECT, authenticated): merge 2 policies ──
DROP POLICY IF EXISTS "school_exams_school_admin_select" ON public.school_exams;
DROP POLICY IF EXISTS "school_exams_student_select" ON public.school_exams;
CREATE POLICY "school_exams_select_merged" ON public.school_exams
  FOR SELECT TO authenticated
  USING (
  (((school_id = get_admin_school_id()) OR is_school_admin_of(school_id)))
  OR (((status = ANY (ARRAY['scheduled'::text, 'active'::text])) AND (school_id IN ( SELECT students.school_id
   FROM students
  WHERE ((students.auth_user_id = ( SELECT auth.uid() AS uid)) AND (students.school_id IS NOT NULL))))))
  );

-- ── public.school_questions (SELECT, authenticated): merge 2 policies ──
DROP POLICY IF EXISTS "school_questions_school_admin_select" ON public.school_questions;
DROP POLICY IF EXISTS "school_questions_student_select" ON public.school_questions;
CREATE POLICY "school_questions_select_merged" ON public.school_questions
  FOR SELECT TO authenticated
  USING (
  (((school_id = get_admin_school_id()) OR is_school_admin_of(school_id)))
  OR (((approved = true) AND (school_id IN ( SELECT students.school_id
   FROM students
  WHERE ((students.auth_user_id = ( SELECT auth.uid() AS uid)) AND (students.school_id IS NOT NULL))))))
  );

-- ── public.student_skill_state (SELECT, authenticated): merge 2 policies ──
DROP POLICY IF EXISTS "student_skill_state_own_select" ON public.student_skill_state;
DROP POLICY IF EXISTS "student_skill_state_parent_select" ON public.student_skill_state;
CREATE POLICY "student_skill_state_select_merged" ON public.student_skill_state
  FOR SELECT TO authenticated
  USING (
  (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  OR (is_guardian_of(student_id))
  );

-- ── public.user_roles (SELECT, authenticated): merge 2 policies ──
DROP POLICY IF EXISTS "user_roles_admin" ON public.user_roles;
DROP POLICY IF EXISTS "user_roles_select" ON public.user_roles;
CREATE POLICY "user_roles_select_merged" ON public.user_roles
  FOR SELECT TO authenticated
  USING (
  ((( SELECT auth.uid() AS uid) IN ( SELECT admin_users.auth_user_id
   FROM admin_users
  WHERE (admin_users.is_active = true))))
  OR (((auth_user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT auth.uid() AS uid) IN ( SELECT admin_users.auth_user_id
   FROM admin_users
  WHERE (admin_users.is_active = true)))))
  );
