-- Platform Security Layer — Phase 3 Wave 3: whatsapp-notify
-- Seeds quota profile, route policy, and internal caller registrations
-- for the whatsapp-notify Edge Function.
--
-- whatsapp-notify is an internal-service-only function: only signed Next.js
-- routes (notifications-whatsapp-route, school-admin-parents-route,
-- synthesis-parent-share-route) may call it. No student JWT is admitted.

-- ── 1. Quota profile ────────────────────────────────────────────────────────
-- Token limits are zero (WhatsApp Cloud API, not an LLM token-counted API).
-- Cost limits cover WhatsApp Business API session fees billed to the project.

INSERT INTO public.security_quota_profiles (
  name, scope, role, route,
  requests_daily_limit, requests_monthly_limit,
  input_tokens_daily_limit, input_tokens_monthly_limit,
  output_tokens_daily_limit, output_tokens_monthly_limit,
  estimated_cost_daily_limit, estimated_cost_monthly_limit,
  max_concurrent_requests, circuit_breaker_threshold, enforcement_mode
) VALUES (
  'whatsapp-notify-internal_service',
  'internal_service',
  'internal_service',
  'whatsapp-notify',
  500,   15000,
  500,   15000,
  0,     0,
  0.10,  3.00,
  10, 5, 'enforce'
)
ON CONFLICT (name) DO UPDATE SET
  scope                       = EXCLUDED.scope,
  role                        = EXCLUDED.role,
  route                       = EXCLUDED.route,
  requests_daily_limit        = EXCLUDED.requests_daily_limit,
  requests_monthly_limit      = EXCLUDED.requests_monthly_limit,
  input_tokens_daily_limit    = EXCLUDED.input_tokens_daily_limit,
  input_tokens_monthly_limit  = EXCLUDED.input_tokens_monthly_limit,
  output_tokens_daily_limit   = EXCLUDED.output_tokens_daily_limit,
  output_tokens_monthly_limit = EXCLUDED.output_tokens_monthly_limit,
  estimated_cost_daily_limit  = EXCLUDED.estimated_cost_daily_limit,
  estimated_cost_monthly_limit= EXCLUDED.estimated_cost_monthly_limit,
  max_concurrent_requests     = EXCLUDED.max_concurrent_requests,
  circuit_breaker_threshold   = EXCLUDED.circuit_breaker_threshold,
  enforcement_mode            = EXCLUDED.enforcement_mode,
  updated_at                  = now();

-- ── 2. Route policy ─────────────────────────────────────────────────────────
-- Only signed internal callers may access whatsapp-notify.
-- allow_jwt = false, allow_service_role = false, allow_signed_internal = true.
-- policy_key is auto-generated by DB trigger as:
--   route||'|'||school_id||'|'||role||'|'||caller_type||'|'||internal_caller_id
-- NULLs in that expression produce NULL so the trigger uses COALESCE to an
-- empty-string sentinel. We use ON CONFLICT (policy_key) DO NOTHING.

INSERT INTO public.security_route_policies (
  route, school_id, role, caller_type, internal_caller_id,
  quota_profile_id,
  enforcement_mode,
  allow_signed_internal, allow_jwt, allow_service_role,
  is_enabled
)
SELECT
  'whatsapp-notify',
  NULL,
  NULL,
  'internal_service',
  NULL,
  p.id,
  'enforce',
  true, false, false,
  true
FROM public.security_quota_profiles p
WHERE p.name = 'whatsapp-notify-internal_service'
ON CONFLICT (policy_key) DO NOTHING;

-- ── 3. Internal caller registrations ────────────────────────────────────────
-- Three Next.js routes that POST to whatsapp-notify must be registered so the
-- security_resolve_internal_caller RPC can verify their HMAC-SHA256 signatures.
-- The name values here MUST match the caller strings passed to
-- buildInternalCallerHeaders in each Next.js route file (case-sensitive).

INSERT INTO public.security_internal_callers (
  name, owner, description, status, caller_kind, quota_profile_id
)
SELECT
  caller_name,
  'platform',
  caller_desc,
  'active',
  'service_name',
  p.id
FROM (
  VALUES
    ('notifications-whatsapp-route',  'Next.js /api/notifications/whatsapp route posting to whatsapp-notify'),
    ('school-admin-parents-route',    'Next.js /api/school-admin/parents route posting to whatsapp-notify'),
    ('synthesis-parent-share-route',  'Next.js /api/synthesis/parent-share route posting to whatsapp-notify')
) AS callers(caller_name, caller_desc)
CROSS JOIN public.security_quota_profiles p
WHERE p.name = 'whatsapp-notify-internal_service'
ON CONFLICT (name) DO UPDATE SET
  status      = EXCLUDED.status,
  description = EXCLUDED.description;
