-- 20260903190000_p2_5_phase2c_merge_rls_policies_batch2.sql
--
-- P2-5 phase 2, batch 2 of Category B (2026-09-03 launch audit, CEO-
-- approved "full consolidation, small batches with tests" — follow-up to
-- batch 1's 20260903180000, same methodology).
--
-- Scope: all remaining (table, command, role) groups with exactly 2
-- PERMISSIVE policies, same role, that batch 1 didn't cover — 19 tables,
-- 23 groups. Deliberately excludes the 3-6-policy groups (quiz_responses
-- SELECT, foxy_chat_messages SELECT, students, etc.) and the `students`
-- table specifically (its own dedicated recursion-guard test section
-- treats it as an apex/high-sensitivity case; merging it deserves standalone
-- handling, not a routine batch) — tracked as later batches.
--
-- METHOD (unchanged from batch 1): every USING/WITH CHECK clause below was
-- generated by a script from the EXACT live pg_policies qual/with_check
-- text pulled immediately before writing this file — never hand-retyped.
-- INSERT-only groups merge WITH CHECK only (INSERT policies have no
-- USING); UPDATE groups merge both USING and WITH CHECK (each
-- independently ORed across the source policies, preserving the exact
-- pre-existing pre-row/post-row semantics of each).
--
-- Also unchanged: only merged groups sharing the identical `roles` value.
-- xp_transactions and teacher_parent_messages each ALSO carry an
-- additional policy with a DIFFERENT roles value on the very same command
-- (xp_txn_parent_select is `{public}` where the two merged here are
-- `{authenticated}`) — deliberately left untouched; a `{public}` policy
-- applies to every role including authenticated, so folding it into an
-- `authenticated`-only merged policy would either silently drop anon/other
-- access (if merged as `TO authenticated`) or widen the other two policies'
-- intended scope (if merged as `TO public`) — a real semantic question, not
-- a hygiene merge, deferred rather than guessed at.
--
-- storage.objects (INSERT): note this is Supabase's own Storage system
-- table, not an application table under `public`. The two merged policies
-- are self-contained per bucket (each ANDs its own `bucket_id = '...'`
-- check), so ORing them together changes nothing about which upload
-- succeeds for which bucket — merging is safe. Storage RLS is ordinary
-- pg_policies underneath; the Supabase Storage dashboard reads/writes the
-- same catalog, so a policy rename is transparent to it.
--
-- Recursion-guard ledger: see the companion update to
-- apps/host/src/__tests__/rls-no-cross-table-recursion.test.ts in this same
-- PR for the GRANDFATHERED_INLINE_POLICIES swap this batch requires (every
-- one of these tables' "_own_*"-style policies inlines the same
-- `student_id IN (SELECT s.id FROM students s WHERE s.auth_user_id =
-- auth.uid())` cross-table pattern as batch 1, so every merge here is
-- expected to trip the same "NEW/RENAMED inline policy" detection for a
-- pre-existing, not new, risk).

-- -- public.bloom_progression (INSERT, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "Students can insert own bloom_progression" ON public.bloom_progression;
DROP POLICY IF EXISTS "bloom_progression_own_insert" ON public.bloom_progression;
CREATE POLICY "bloom_progression_insert_merged" ON public.bloom_progression
  FOR INSERT TO authenticated
  WITH CHECK (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );

-- -- public.bloom_progression (UPDATE, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "Students can update own bloom_progression" ON public.bloom_progression;
DROP POLICY IF EXISTS "bloom_progression_own_update" ON public.bloom_progression;
CREATE POLICY "bloom_progression_update_merged" ON public.bloom_progression
  FOR UPDATE TO authenticated
  USING (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  )
  WITH CHECK (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );

-- -- public.classes (INSERT, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "School admins can insert school classes" ON public.classes;
DROP POLICY IF EXISTS "Teachers can insert classes" ON public.classes;
CREATE POLICY "classes_insert_merged" ON public.classes
  FOR INSERT TO authenticated
  WITH CHECK (
  (((school_id IS NOT NULL) AND is_school_admin_of(school_id)))
  OR ((EXISTS ( SELECT 1
   FROM teachers
  WHERE (teachers.auth_user_id = ( SELECT auth.uid() AS uid)))))
  );

-- -- public.engagement_events (INSERT, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "engagement_events_own_insert" ON public.engagement_events;
DROP POLICY IF EXISTS "engagement_events_student_insert" ON public.engagement_events;
CREATE POLICY "engagement_events_insert_merged" ON public.engagement_events
  FOR INSERT TO authenticated
  WITH CHECK (
  (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  OR ((student_id = get_my_student_id()))
  );

-- -- public.foxy_chat_messages (INSERT, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "Students can insert own foxy messages" ON public.foxy_chat_messages;
DROP POLICY IF EXISTS "foxy_chat_messages_own_insert" ON public.foxy_chat_messages;
CREATE POLICY "foxy_chat_messages_insert_merged" ON public.foxy_chat_messages
  FOR INSERT TO authenticated
  WITH CHECK (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );

-- -- public.foxy_sessions (INSERT, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "Students can insert own foxy sessions" ON public.foxy_sessions;
DROP POLICY IF EXISTS "foxy_sessions_own_insert" ON public.foxy_sessions;
CREATE POLICY "foxy_sessions_insert_merged" ON public.foxy_sessions
  FOR INSERT TO authenticated
  WITH CHECK (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );

-- -- public.foxy_sessions (UPDATE, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "Students can update own foxy sessions" ON public.foxy_sessions;
DROP POLICY IF EXISTS "foxy_sessions_own_update" ON public.foxy_sessions;
CREATE POLICY "foxy_sessions_update_merged" ON public.foxy_sessions
  FOR UPDATE TO authenticated
  USING (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  )
  WITH CHECK (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );

-- -- storage.objects (INSERT, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "Admin upload cms media" ON storage.objects;
DROP POLICY IF EXISTS "Students upload own scans" ON storage.objects;
CREATE POLICY "objects_insert_merged" ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
  (((bucket_id = 'cms-media'::text) AND (EXISTS ( SELECT 1
   FROM admin_users
  WHERE ((admin_users.auth_user_id = auth.uid()) AND (admin_users.is_active = true))))))
  OR (((bucket_id = 'student-scans'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)))
  );

-- -- public.product_events (INSERT, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "product_events_own_insert" ON public.product_events;
DROP POLICY IF EXISTS "product_events_student_insert" ON public.product_events;
CREATE POLICY "product_events_insert_merged" ON public.product_events
  FOR INSERT TO authenticated
  WITH CHECK (
  (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  OR ((student_id = get_my_student_id()))
  );

-- -- public.quiz_responses (INSERT, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "Students can insert own quiz_responses" ON public.quiz_responses;
DROP POLICY IF EXISTS "quiz_responses_own_insert" ON public.quiz_responses;
CREATE POLICY "quiz_responses_insert_merged" ON public.quiz_responses
  FOR INSERT TO authenticated
  WITH CHECK (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );

-- -- public.quiz_sessions (INSERT, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "Students can insert own quiz_sessions" ON public.quiz_sessions;
DROP POLICY IF EXISTS "quiz_sessions_own_insert" ON public.quiz_sessions;
CREATE POLICY "quiz_sessions_insert_merged" ON public.quiz_sessions
  FOR INSERT TO authenticated
  WITH CHECK (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );

-- -- public.quiz_sessions (SELECT, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "quiz_sessions_admin_select" ON public.quiz_sessions;
DROP POLICY IF EXISTS "quiz_sessions_own_select" ON public.quiz_sessions;
CREATE POLICY "quiz_sessions_select_merged" ON public.quiz_sessions
  FOR SELECT TO authenticated
  USING (
  (is_admin())
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );

-- -- public.quiz_sessions (UPDATE, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "Students can update own quiz_sessions" ON public.quiz_sessions;
DROP POLICY IF EXISTS "quiz_sessions_own_update" ON public.quiz_sessions;
CREATE POLICY "quiz_sessions_update_merged" ON public.quiz_sessions
  FOR UPDATE TO authenticated
  USING (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  )
  WITH CHECK (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );

-- -- public.student_achievements (INSERT, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "Students can insert own achievements" ON public.student_achievements;
DROP POLICY IF EXISTS "student_achievements_own_insert" ON public.student_achievements;
CREATE POLICY "student_achievements_insert_merged" ON public.student_achievements
  FOR INSERT TO authenticated
  WITH CHECK (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );

-- -- public.student_learning_profiles (UPDATE, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "Students can update own learning profiles" ON public.student_learning_profiles;
DROP POLICY IF EXISTS "student_learning_profiles_own_update" ON public.student_learning_profiles;
CREATE POLICY "student_learning_profiles_update_merged" ON public.student_learning_profiles
  FOR UPDATE TO authenticated
  USING (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  )
  WITH CHECK (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );

-- -- public.teacher_parent_messages (INSERT, public): merge 2 policies --
DROP POLICY IF EXISTS "tp_messages_guardian_insert" ON public.teacher_parent_messages;
DROP POLICY IF EXISTS "tp_messages_teacher_insert" ON public.teacher_parent_messages;
CREATE POLICY "teacher_parent_messages_insert_merged" ON public.teacher_parent_messages
  FOR INSERT TO public
  WITH CHECK (
  (((sender_role = 'guardian'::text) AND (sender_auth_user_id = ( SELECT auth.uid() AS uid)) AND (thread_id IN ( SELECT th.id
   FROM (teacher_parent_threads th
     JOIN guardians g ON ((g.id = th.guardian_id)))
  WHERE (g.auth_user_id = ( SELECT auth.uid() AS uid))))))
  OR (((sender_role = 'teacher'::text) AND (sender_auth_user_id = ( SELECT auth.uid() AS uid)) AND (thread_id IN ( SELECT th.id
   FROM (teacher_parent_threads th
     JOIN teachers t ON ((t.id = th.teacher_id)))
  WHERE (t.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );

-- -- public.teacher_parent_messages (SELECT, public): merge 2 policies --
DROP POLICY IF EXISTS "tp_messages_guardian_select" ON public.teacher_parent_messages;
DROP POLICY IF EXISTS "tp_messages_teacher_select" ON public.teacher_parent_messages;
CREATE POLICY "teacher_parent_messages_select_merged" ON public.teacher_parent_messages
  FOR SELECT TO public
  USING (
  ((thread_id IN ( SELECT th.id
   FROM (teacher_parent_threads th
     JOIN guardians g ON ((g.id = th.guardian_id)))
  WHERE (g.auth_user_id = ( SELECT auth.uid() AS uid)))))
  OR ((thread_id IN ( SELECT th.id
   FROM (teacher_parent_threads th
     JOIN teachers t ON ((t.id = th.teacher_id)))
  WHERE (t.auth_user_id = ( SELECT auth.uid() AS uid)))))
  );

-- -- public.teacher_remediation_assignments (INSERT, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "teacher_remediation_assignments_own_insert" ON public.teacher_remediation_assignments;
DROP POLICY IF EXISTS "teacher_remediation_assignments_teacher_insert" ON public.teacher_remediation_assignments;
CREATE POLICY "teacher_remediation_assignments_insert_merged" ON public.teacher_remediation_assignments
  FOR INSERT TO authenticated
  WITH CHECK (
  (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  OR (((teacher_id IN ( SELECT t.id
   FROM teachers t
  WHERE (t.auth_user_id = ( SELECT auth.uid() AS uid)))) AND is_teacher_of(student_id) AND (class_id IN ( SELECT ct.class_id
   FROM (class_teachers ct
     JOIN teachers t ON ((t.id = ct.teacher_id)))
  WHERE (t.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );

-- -- public.teacher_remediation_assignments (SELECT, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "teacher_remediation_assignments_own_select" ON public.teacher_remediation_assignments;
DROP POLICY IF EXISTS "teacher_remediation_assignments_teacher_select" ON public.teacher_remediation_assignments;
CREATE POLICY "teacher_remediation_assignments_select_merged" ON public.teacher_remediation_assignments
  FOR SELECT TO authenticated
  USING (
  (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  OR (((teacher_id IN ( SELECT t.id
   FROM teachers t
  WHERE (t.auth_user_id = ( SELECT auth.uid() AS uid)))) AND is_teacher_of(student_id)))
  );

-- -- public.teacher_remediation_assignments (UPDATE, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "teacher_remediation_assignments_own_update" ON public.teacher_remediation_assignments;
DROP POLICY IF EXISTS "teacher_remediation_assignments_teacher_update" ON public.teacher_remediation_assignments;
CREATE POLICY "teacher_remediation_assignments_update_merged" ON public.teacher_remediation_assignments
  FOR UPDATE TO authenticated
  USING (
  (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  OR (((teacher_id IN ( SELECT t.id
   FROM teachers t
  WHERE (t.auth_user_id = ( SELECT auth.uid() AS uid)))) AND is_teacher_of(student_id)))
  )
  WITH CHECK (
  (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  OR (((teacher_id IN ( SELECT t.id
   FROM teachers t
  WHERE (t.auth_user_id = ( SELECT auth.uid() AS uid)))) AND is_teacher_of(student_id)))
  );

-- -- public.topic_mastery (INSERT, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "Students can insert own topic_mastery" ON public.topic_mastery;
DROP POLICY IF EXISTS "topic_mastery_own_insert" ON public.topic_mastery;
CREATE POLICY "topic_mastery_insert_merged" ON public.topic_mastery
  FOR INSERT TO authenticated
  WITH CHECK (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );

-- -- public.topic_mastery (UPDATE, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "Students can update own topic_mastery" ON public.topic_mastery;
DROP POLICY IF EXISTS "topic_mastery_own_update" ON public.topic_mastery;
CREATE POLICY "topic_mastery_update_merged" ON public.topic_mastery
  FOR UPDATE TO authenticated
  USING (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  )
  WITH CHECK (
  ((student_id = get_my_student_id()))
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );

-- -- public.xp_transactions (SELECT, authenticated): merge 2 policies --
DROP POLICY IF EXISTS "xp_transactions_admin_select" ON public.xp_transactions;
DROP POLICY IF EXISTS "xp_transactions_own_select" ON public.xp_transactions;
CREATE POLICY "xp_transactions_select_merged" ON public.xp_transactions
  FOR SELECT TO authenticated
  USING (
  (is_admin())
  OR (((student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT s.id
   FROM students s
  WHERE (s.auth_user_id = ( SELECT auth.uid() AS uid))))))
  );
