-- lint:allow-placeholder
-- Migration: 20260813085254_fix_csr_chapter_universe_ambiguity.sql
-- Purpose: SUPERSEDED no-op placeholder. See 20260815000006_fix_csr_chapter_universe_ambiguity.sql.
--
-- ============================================================================
-- WHY THIS FILE IS NOW A NO-OP (P0-7 fix, comprehensive code review 2026-08-20)
-- ============================================================================
-- This file and 20260815000006_fix_csr_chapter_universe_ambiguity.sql were
-- byte-identical (both fixed the same `compute_subject_readiness` 42702
-- ambiguous-column bug, verified `diff` clean / matching md5
-- c4a7fdb3a1c538d2b0ede9adedd817cb). That duplication was itself a problem:
--
--   1. Out-of-order relative to the migration it corrects. This file's
--      timestamp (20260813085254) sorts BEFORE both 20260813144550
--      (recovery migration, documented "ALREADY APPLIED ON PRODUCTION") and
--      20260815000005_fix_compute_subject_readiness_ambiguous_chapter_number.sql
--      (the migration that (re)introduces the ambiguous chapter_number bug
--      this fix corrects). On a FRESH database replay, applying the fix
--      before the bug it fixes even exists meant the sequence was:
--        fix (this file, backdated) -> ... -> re-break (20260815000005)
--        -> re-fix (20260815000006, the real corrected version).
--      i.e. the same logical fix was recorded twice in the ledger, and a
--      fresh chain replay went fix -> re-break -> re-fix instead of a single
--      clean fix.
--   2. It cannot simply be deleted: this version may already be recorded as
--      APPLIED in `supabase_migrations.schema_migrations` on some
--      environment (it shipped in the same PR batch as 20260815000006 per
--      20260813144550's recovery-migration header, which lists both
--      20260813085254 and 20260815000006 as "legitimately-pending
--      migrations from that PR"). Deleting a committed, possibly-applied
--      migration file breaks `supabase db push --include-all` parity
--      (P0-6's verify-migration-ledger.sh would report it as
--      "applied on remote but not committed").
--
-- RESOLUTION: this file is reduced to an inert no-op placeholder. The file
-- (and its ledger entry) stays present for parity on any environment that
-- already applied it; a fresh replay now applies this as a true no-op, lets
-- 20260815000005 introduce the ambiguity bug once, and lets
-- 20260815000006_fix_csr_chapter_universe_ambiguity.sql (unchanged,
-- authoritative) fix it once. No functional change on any environment: this
-- version's original body was identical to 20260815000006's, so an
-- environment that already applied THIS version already holds the correct
-- function definition, and 20260815000006 applying afterward is itself an
-- idempotent CREATE OR REPLACE with the same body.
--
-- Opted out of scripts/lint-migrations.js's SELECT-1-placeholder rejection
-- via the `-- lint:allow-placeholder` marker on line 1, per the established
-- convention (see e.g. 20260509130000_mcp_applied_placeholder.sql).
--
-- Rollback: N/A — this migration never changes schema/data going forward;
-- the authoritative fix lives entirely in 20260815000006.

-- No-op
SELECT 1 WHERE FALSE;
