-- Migration: KPI metric contracts table (P1-6)
-- Audit remediation 2026-08-06: Creates formal metric contract registry.

CREATE TABLE IF NOT EXISTS public.kpi_metric_contracts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  metric_name text NOT NULL UNIQUE,
  metric_version integer NOT NULL DEFAULT 1,
  business_question text NOT NULL,
  decision_supported text,
  audience text NOT NULL CHECK (audience IN (
    'product', 'content', 'learning_science', 'school_admin',
    'super_admin', 'investor', 'parent', 'regulator'
  )),
  accountabible_owner text NOT NULL,
  steward text,
  grain_entity text NOT NULL,
  eligible_population text,
  numerator_definition text NOT NULL,
  denominator_definition text NOT NULL,
  units text NOT NULL DEFAULT 'count',
  aggregation_method text NOT NULL DEFAULT 'SUM',
  event_time_field text,
  reporting_timezone text DEFAULT 'Asia/Kolkata',
  reporting_window text DEFAULT 'daily',
  late_data_policy text DEFAULT 'exclude',
  required_dimensions text[],
  minimum_group_size integer DEFAULT 5,
  filters text[],
  exclusions text[],
  authoritative_sources text[] NOT NULL,
  transformation_version text,
  source_precedence text,
  freshness_slo interval DEFAULT '24 hours',
  expected_range jsonb,
  anomaly_detection_rule text,
  reconciliation_method text,
  privacy_classification text NOT NULL DEFAULT 'internal' CHECK (privacy_classification IN (
    'public', 'internal', 'tenant_confidential', 'restricted'
  )),
  required_access_role text NOT NULL DEFAULT 'service_role',
  retention_policy text DEFAULT '1_year',
  export_rule text DEFAULT 'prohibited',
  known_limitations text[],
  prohibited_interpretations text[],
  change_approval text,
  effective_from timestamptz DEFAULT now(),
  deprecated_at timestamptz,
  deprecation_superseded_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE public.kpi_metric_contracts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access kpi_metric_contracts"
  ON public.kpi_metric_contracts FOR ALL
  TO service_role
  USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated can read metric contracts"
  ON public.kpi_metric_contracts FOR SELECT
  TO authenticated
  USING (true);

-- Seed top 10 KPIs per governance reference
INSERT INTO public.kpi_metric_contracts
  (metric_name, business_question, audience, accountabible_owner, grain_entity,
   numerator_definition, denominator_definition, units, authoritative_sources,
   freshness_slo, privacy_classification, required_access_role,
   known_limitations, prohibited_interpretations)
VALUES
  -- Learning Effectiveness
  ('mastery_growth_rate',
   'What percentage of active concepts show mastery improvement over the last 30 days?',
   'learning_science',
   'data-platform',
   'learner_concept',
   'COUNT(DISTINCT concept_id) WHERE mastery_estimate_increased AND evidence_fresh',
   'COUNT(DISTINCT concept_id) WHERE active_learning',
   'percentage',
   ARRAY['concept_mastery', 'learning_events', 'quiz_sessions'],
   '24 hours',
   'internal',
   'service_role',
   ARRAY['Provisional IRT parameters may skew estimates', 'Excludes concepts with insufficient evidence (<3 attempts)'],
   ARRAY['Do not interpret as grade-level proficiency', 'Not a replacement for standardized assessment']),

  ('retention_at_interval',
   'What proportion of concepts mastered are successfully recalled at 7/30/90 day intervals?',
   'learning_science',
   'data-platform',
   'learner_concept_interval',
   'COUNT(concept_id) WHERE recall_successful',
   'COUNT(concept_id) WHERE review_due AND retention_checked',
   'percentage',
   ARRAY['spaced_repetition_cards', 'quiz_responses', 'concept_mastery'],
   '24 hours',
   'internal',
   'service_role',
   ARRAY['Requires minimum review interval to be meaningful', 'Self-selection bias: only reviewed items are counted'],
   ARRAY['Not a measure of forgetting rate', 'Does not account for difficulty of concept']),

  -- Product & Instructional Use
  ('daily_active_learners',
   'How many unique learners complete at least one learning action per day?',
   'product',
   'data-platform',
   'student_day',
   'COUNT(DISTINCT student_id)',
   'NULL (absolute count)',
   'count',
   ARRAY['quiz_sessions', 'learning_events', 'foxy_sessions'],
   '12 hours',
   'internal',
   'service_role',
   ARRAY['Includes demo accounts', 'Includes both organic and assigned activity'],
   ARRAY['Do not equate activity with learning', 'Do not compare across different school calendars']),

  ('today_recommendation_acceptance_rate',
   'What percentage of Today recommendations are accepted and completed?',
   'product',
   'data-platform',
   'recommendation',
   'COUNT(recommendation_id) WHERE status = ''completed''',
   'COUNT(recommendation_id) WHERE status IN (''presented'', ''accepted'', ''completed'')',
   'percentage',
   ARRAY['recommendations', 'quiz_sessions', 'learning_events'],
   '12 hours',
   'internal',
   'service_role',
   ARRAY['Completion requires full session finish', 'Recommendations may be completed later (same-day attribution)'],
   ARRAY['Not a direct measure of recommendation quality', 'Acceptance influenced by UI position and timing']),

  -- Safety & Quality
  ('safety_incident_rate',
   'How many safety incidents per 1000 active learners per day?',
   'super_admin',
   'data-platform',
   'platform_day',
   'COUNT(safety_incident_id)',
   'COUNT(DISTINCT active_learner) / 1000',
   'per_1000',
   ARRAY['safeguarding_escalations', 'foxy_chat_messages', 'ai_quality_metrics'],
   '4 hours',
   'restricted',
   'service_role',
   ARRAY['Only captures automated detections + manual reports', 'Severity classification is provisional'],
   ARRAY['Do not share raw counts externally', 'Do not break down by demographic without safety review']),

  ('rag_grounding_rate',
   'What percentage of Foxy responses have at least one grounded citation?',
   'content',
   'data-platform',
   'foxy_response',
   'COUNT(response_id) WHERE grounding_citation_count > 0',
   'COUNT(response_id) WHERE foxy_response_type IN (''learn'', ''explain'', ''practice'')',
   'percentage',
   ARRAY['grounded_ai_traces', 'foxy_chat_messages', 'rag_retrieval_logs'],
   '4 hours',
   'internal',
   'service_role',
   ARRAY['Citation presence != citation correctness', 'Baseline rate excludes refusal/fallback responses'],
   ARRAY['Do not equate grounding rate with response quality', 'Not a safety metric']),

  -- Reliability & Operations
  ('event_persistence_success_rate',
   'What percentage of accepted domain events reach terminal processed state?',
   'super_admin',
   'data-platform',
   'event',
   'COUNT(event_id) WHERE processing_status = ''processed''',
   'COUNT(event_id) WHERE processing_status IN (''accepted'', ''processed'', ''failed'')',
   'percentage',
   ARRAY['state_events', 'domain_events', 'projector_run_log'],
   '1 hour',
   'internal',
   'service_role',
   ARRAY['Excludes events still in-flight (< 1h old)', 'Dead-letter events counted as failures'],
   ARRAY['99.9% is an availability target, not a correctness guarantee']),

  ('p95_quiz_submit_latency',
   'What is the 95th percentile end-to-end latency for quiz submissions?',
   'super_admin',
   'data-platform',
   'quiz_session',
   'PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY time_taken_seconds)',
   'NULL (statistical measure)',
   'seconds',
   ARRAY['quiz_sessions', 'api_request_logs'],
   '1 hour',
   'internal',
   'service_role',
   ARRAY['Client-reported time may include network latency', 'Server-side measured differently than client-perceived'],
   ARRAY['Not to be used as SLA for individual requests', 'Does not reflect mobile experience']),

  -- Institutional Outcomes
  ('school_adoption_rate',
   'What percentage of active learners come from schools with >80% class enrollment?',
   'school_admin',
   'data-platform',
   'school',
   'COUNT(DISTINCT student_id) WHERE school_enrollment_rate >= 0.8',
   'COUNT(DISTINCT student_id)',
   'percentage',
   ARRAY['class_enrollments', 'students', 'schools'],
   '24 hours',
   'tenant_confidential',
   'service_role',
   ARRAY['Enrollment rate based on class roster data', 'Excludes B2C (non-school) learners'],
   ARRAY['Not a measure of learning outcomes', 'Do not rank or publish school-specific rates']),

  ('teacher_action_rate',
   'What percentage of teachers perform at least one action (assignment/insight/remediation) per week?',
   'product',
   'data-platform',
   'teacher_week',
   'COUNT(DISTINCT teacher_id) WHERE weekly_actions > 0',
   'COUNT(DISTINCT teacher_id) WHERE active_account',
   'percentage',
   ARRAY['teacher_actions', 'assignments', 'intervention_alerts'],
   '24 hours',
   'internal',
   'service_role',
   ARRAY['Action definition includes both proactive and reactive actions', 'Excludes teachers with no assigned classes'],
   ARRAY['Not a measure of teacher effectiveness', 'Low rate may indicate training gap rather than product gap'])
ON CONFLICT (metric_name) DO UPDATE SET
  metric_version = kpi_metric_contracts.metric_version + 1,
  numerator_definition = EXCLUDED.numerator_definition,
  denominator_definition = EXCLUDED.denominator_definition,
  known_limitations = EXCLUDED.known_limitations,
  updated_at = now();
