-- Migration: 20260813000004_teacher_assignment_drafts.sql
-- Purpose: Foxy North-Star Phase 5 (K5 — Play / teacher-authored assignment
--          drafts). NEW TABLE for teacher-owned draft assignments generated by
--          the Foxy oracle-validated question generator BEFORE publication.
--          A draft is a private, teacher-only workspace: it holds the
--          candidate questions + the oracle validation report so the teacher
--          can review, tweak, and publish (or discard) without exposing
--          anything to students or parents. Publication is a SEPARATE explicit
--          action (out of scope of this migration) that materializes the draft
--          into an assignments row and stamps `published_assignment_id` here.
--
-- Spec: docs/superpowers/specs/2026-08-05-foxy-north-star-alignment-design.md
--       (Phase 5 K5 — Play draft workspace; P8 same-migration RLS; P6 oracle).
--
-- ─── P8 same-migration RLS (mandatory for new tables) ────────────────────────
-- Because drafts contain candidate content that is deliberately UNVETTED until
-- the teacher approves it, the RLS posture is intentionally MINIMAL:
--   * teacher_own_all — the drafting teacher can SELECT/INSERT/UPDATE/DELETE
--     their OWN drafts (resolved via teachers.auth_user_id = auth.uid()).
--   * service_role_all — canonical writer for the oracle-fill + publish flow.
--   * NO student policy. NO parent policy. NO peer-teacher policy. This is
--     DELIBERATE — a draft is not curriculum until it becomes an assignments
--     row via the explicit publish action. Exposing pre-review candidate items
--     to students would violate P6 (question quality) because oracle_report
--     may flag defects the teacher chose not to fix. Do not add a student or
--     parent policy in a future migration without a paired spec approval.
--
-- ─── Idempotency / additive posture ──────────────────────────────────────────
--   * CREATE TABLE IF NOT EXISTS, ENABLE RLS is idempotent, DROP POLICY IF
--     EXISTS + CREATE POLICY, CREATE OR REPLACE FUNCTION, DROP TRIGGER IF
--     EXISTS + CREATE TRIGGER, CREATE INDEX IF NOT EXISTS. Fully re-runnable.
--   * No DROP TABLE / DROP COLUMN. No RBAC seeding — teachers already hold
--     the effective "manage own drafts" surface through this table's RLS.
--
-- Owner: architect. Reviewer chain: backend (draft/publish API routes),
-- frontend (Play UI), ai-engineer (oracle_report shape), assessment (P6
-- oracle contract), testing.

BEGIN;

-- =============================================================================
-- 1. Table
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.teacher_assignment_drafts (
  id                       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  teacher_id               uuid NOT NULL REFERENCES public.teachers(id) ON DELETE CASCADE,
  -- Nullable: teacher can start a draft before deciding which class receives it.
  class_id                 uuid NULL REFERENCES public.classes(id) ON DELETE SET NULL,
  subject                  text NULL,
  -- P5: grade is a STRING ("6".."12"), never an integer. Bounded length so a
  -- rogue value can't shadow-page the row.
  grade                    text NULL CHECK (grade IS NULL OR (length(grade) BETWEEN 1 AND 4)),
  -- Human-readable chapter label the teacher typed (optional; chapter_id is the
  -- canonical anchor when the draft is bound to a curriculum row).
  chapter                  text NULL,
  chapter_id               uuid NULL,
  -- Oracle-validated candidate questions. Shape is P6-compatible (question_text,
  -- 4 options, correct_answer_index, explanation, difficulty, bloom_level) but
  -- jsonb here so drafts can carry generator-side scaffolding pre-publish.
  questions                jsonb NOT NULL,
  -- Oracle validation report snapshot (deterministic + LLM-grader verdicts).
  -- Nullable so a teacher can save a hand-authored draft without invoking the
  -- oracle; the publish action requires it non-null (enforced at the API layer).
  oracle_report            jsonb NULL,
  status                   text NOT NULL DEFAULT 'draft'
                             CHECK (status IN ('draft', 'published', 'discarded')),
  -- Set when the draft is published — soft pointer to assignments.id.
  published_assignment_id  uuid NULL,
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.teacher_assignment_drafts IS
  'Foxy Phase 5 K5 (Play): teacher-owned draft workspace for oracle-validated question sets. Deliberately invisible to students and parents until a published_assignment_id is stamped by the publish action — do NOT add a student/parent RLS policy without paired spec approval.';
COMMENT ON COLUMN public.teacher_assignment_drafts.oracle_report IS
  'P6: snapshot of the oracle validation verdict at draft time. Nullable — hand-authored drafts skip it; publish requires it non-null at the API layer.';
COMMENT ON COLUMN public.teacher_assignment_drafts.published_assignment_id IS
  'Soft pointer to assignments.id set by the publish action. Presence + status=''published'' is the "this draft became a real assignment" contract.';

-- =============================================================================
-- 2. RLS — teacher-own only + service-role. NO student/parent policy.
-- =============================================================================

ALTER TABLE public.teacher_assignment_drafts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS teacher_assignment_drafts_teacher_own_all
  ON public.teacher_assignment_drafts;
CREATE POLICY teacher_assignment_drafts_teacher_own_all
  ON public.teacher_assignment_drafts
  FOR ALL
  USING (
    teacher_id IN (
      SELECT id FROM public.teachers WHERE auth_user_id = auth.uid()
    )
  )
  WITH CHECK (
    teacher_id IN (
      SELECT id FROM public.teachers WHERE auth_user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS teacher_assignment_drafts_service_role_all
  ON public.teacher_assignment_drafts;
CREATE POLICY teacher_assignment_drafts_service_role_all
  ON public.teacher_assignment_drafts
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- =============================================================================
-- 3. Indexes (teacher list + status filter — the two hot read paths)
-- =============================================================================

CREATE INDEX IF NOT EXISTS idx_teacher_assignment_drafts_teacher_status
  ON public.teacher_assignment_drafts (teacher_id, status);

-- =============================================================================
-- 4. updated_at trigger (repo-standard shape)
-- =============================================================================

CREATE OR REPLACE FUNCTION public.set_teacher_assignment_drafts_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_teacher_assignment_drafts_updated_at
  ON public.teacher_assignment_drafts;
CREATE TRIGGER trg_teacher_assignment_drafts_updated_at
  BEFORE UPDATE ON public.teacher_assignment_drafts
  FOR EACH ROW EXECUTE FUNCTION public.set_teacher_assignment_drafts_updated_at();

COMMIT;
